### ISSUE TITLE
Faster raid joining and improved raid monitoring

### ISSUE THREAD

**Issue by LordShade** [Masuzu/SarasaBot#10]
the sarasabot window will state that its attempting to join raids, however most of the time it just seems to get stuck in an infinite loop where it consistently pastes the "unclaimed raid screen url" ad infinatum with no way of it stopping.  If often does this with raids that it is too slow to even one punch in, leading to the bot waiting for just a single raid to finish (when it thinks its maxed out at 3) some checks need to be in place for it to check current raids and not just constantly loop until "3 assumed joined" raids are finished. It also happens with no raids joined, sometimes 10minutes in, sometimes 15seconds into opening the program.

A simple fix to this is to add a quick url check where it goes back to the raid selection screen and looks for the image "Joined" on the page. It then takes a note and if this number is less then 3, it finds another raid to join. Have this happen every single 2 loops of unclaimed URL pasting thingy. Ezypzy

The same bug from ZoeyBot's Misc summon selection appears to have made its way over here as well, although I'm starting to suspect it may be my stupid laptops strange hardware scaling in effect because all the scaling options are set to 100% (I have double checked this like 20 + times at this point) its a 1920x1080 screen but the relative screen size is quite small (its only around 15ish inches)

sadly I think twitter integration was a poor design choice in this regard, as the bot is still way slower then a proper raid joiner, such as https://www.gbfraiders.com/ where viramate inclusion allows one to just click "join battle" and it dumps the user straight on the summon page and you can join the fastest filling raids in the game with just how fast this website does things. Copying and pasting is so slow, in this regard. You pretty much have to set the config to avoid all raids below 50%, **it just won't be fast enough to compete, or even one punch.** I would've thought this type of integration would be easy, especially with how you made slave mode in zoeybot.

Also any reason why on my screen sarasabot is consistently opening the summon selection screen upon joining the raid, its actually causing a fair amount of bugs. luascript wise anyway where it has to press the back button and then press the 1st skill, losing absolute vital seconds.... and usually ending the raid because the delay it does mucking with that is actually somewhere around 4seconds, more then enough for a magna boss to die.

**Comment by LordShade** [comment]
Also I paid for 1 week of use for this but I'm pretty disappointed that its breaking every 10minutes or even sometimes breaking within 15seconds of me starting it up, I think you should've released this as a trial to iron out all the bugs @Masuzu 

also about the weird summon selection while in battle where it constantly presses the bottom right crystal, I just saw it get stuck there as well, and what I saw was some kind of rapid clicking where it just kept going and going and going and going and going and GOING

**Comment by LordShade** [comment]
yeah, I left the raid of choice on default settings while I tested it out, trying to join chevaliars who were under the 50% hp barrier was a method of absolute madness because unless you had the best ping or hardware on the planet, you wern't getting the one punch time in before somebody else would beat you, press his instant 900k damage button and kill the chev. (because theres not only 1 person doing this!)

Basically, with the weird summon panel bug, once the battle loads, Sarasa will sometimes "misclick" the summon crystal in the bottom right, opening it up, this delays her ability to click the 1 skill to get points to get reward attributed. Since she has to press the back button, and then press the 1 skill, taking up valuable seconds. She'll also sometimes click too fast (ha) and press the summon on the far left halting the bot completely until user action is taken. The best way to fix this would be to have Sarasa not attempt to make any inputs until the Battle Button is shown on screen.

I've also noted, on tests that have (miraculously) lasted up to 30minutes, that sometimes Sarasa will join a raid, pick a summon from the list and load the battle, only to immediately go into her unclaimed loop before even using her first skill, this could be an error in the code somewhere since it happens "uncommonly" but its annoying when it does because when she's looping her unclaimed checks, Some raids pop up that won't provide rewards. Mostly because of this issue here.

I have a feeling raids where Sarasa has joined, but failed to onepunch because they died before she could take action are being counted incorrectly as successfully joined raids.

**Comment by Masuzu** [comment]
Oh, did you check the value you set for the parameter `ChromeDevToolsWindowDockedOnTheRight`?

**Comment by Masuzu** [comment]
<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr"><a href="https://twitter.com/hashtag/GranblueFantasy?src=hash&amp;ref_src=twsrc%5Etfw">#GranblueFantasy</a> <a href="https://twitter.com/hashtag/%E3%82%B0%E3%83%A9%E3%83%96%E3%83%AB?src=hash&amp;ref_src=twsrc%5Etfw">#グラブル</a> <a href="https://twitter.com/hashtag/SarasaBot?src=hash&amp;ref_src=twsrc%5Etfw">#SarasaBot</a> Following the release of v1.2.0 with much better responsiveness and efficiency farming raids with a high throughput, to be released in the next few hours if all goes well, compensation as a licence extension will be offered. Stay tuned!</p>&mdash; GBTools (@GBFPokerBot) <a href="https://twitter.com/GBFPokerBot/status/937789033446563840?ref_src=twsrc%5Etfw">December 4, 2017</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

**Comment by Masuzu** [comment]
Version 1.2.0 is now out and was tested with Chevalier Magna specifically, for a smoother farming experience. All the changes aforementioned were not included but the most important ones for the time being.
Feel free to create a new ticket for future issue reports.
https://poker-bot.azurewebsites.net/SarasaBot/en/Home/PatchNotes#1-2-0
