### ISSUE TITLE
Invalid Twitter Creds again

### ISSUE THREAD

**Issue by dabudauu** [Masuzu/SarasaBot#100]
UTF-8 Without BOM
Locale is EN
No spaces in between = and keys / tokens
:(

**Comment by ExMachlna** [comment]
Same, incorrect twitter creds

**Comment by ExMachlna** [comment]
Checked my creds with python script, they are correct, so it's definetly bot bug.

**Comment by Michael12jan** [comment]
Same here, able to login twice before got the error.

**Comment by Masuzu** [comment]
It works fine with v1.7.6.
On a PC with an English locale I use UTF8 without BOM. UTF8 otherwise on my other PC with a Japanese locale.

**Comment by ExMachlna** [comment]
UTF-8 without bom worked for me, thanks

**Comment by dabudauu** [comment]
it's been working for a couple days btw, it was just a time-limited error

**Comment by po456asd** [comment]
if anyone got "Invalid Twitter Creds" 
and change encode to UTF-8
if that not reslove try update your pc time.

**Comment by Masuzu** [comment]
Just a final note, if you live in China, it may also be an issue without using a VPN, since Twitter is blocked there.
