### ISSUE TITLE
Mouse cursor being moved too low at the summon tab

### ISSUE THREAD

**Issue by ExMachlna** [Masuzu/SarasaBot#101]
So, i managed to make this thing work for the most part, but it just either scrolls way too much down, or has wrong coordinates for cursor. I showed where cursor is being moved with my amazing paint skills. Then it just helplessly tries to click okay button apparently.
![bug](https://user-images.githubusercontent.com/31672534/37560763-81254448-2a4f-11e8-8bef-bc2d7ce3033e.png)

**Comment by ExMachlna** [comment]
Also, it loops capcha notif sound endlessly for no reason, so i had to turn it off

**Comment by JohnCog** [comment]
Mine is exactly the same. I tried some fixes but nothing worked.

**Comment by Masuzu** [comment]
Do not use Viramate's Favourite summons or else you will loop the captcha due to false positives.

**Comment by Masuzu** [comment]
About the failure to select the summon I can't reproduce it on my side for now but:
- does this happen when there are console messages saying `Selecting party XXX`
- or does it still happen when `Select summonXXX` is the last console message

**Comment by ExMachlna** [comment]
Okay, i think i understand what the issue is. I'm using a laptop with 1366x768 res on windows 10. Tiny part of the okay button being cut off by the toolbar, like shown on the screenshot. I guess that triggers bot to scroll down, and it scrolls a bit too much. I managed to solve this by making chrome full screen before getting to quests page. 
![bug](https://user-images.githubusercontent.com/31672534/37570184-8bb97e02-2afd-11e8-9a8f-01f699e18163.png)

**Comment by Masuzu** [comment]
Oh, that's a good thing to know! Thank you for reporting about this matter.

**Comment by Masuzu** [comment]
The issue was mitigated in the version 1.7.9 https://github.com/Masuzu/SarasaBot/releases/tag/1.7.9
