### ISSUE TITLE
Updated the bot but it thinks it is still version 1.7.6

### ISSUE THREAD

**Issue by Twelve11** [Masuzu/SarasaBot#104]
Hi, as the title suggests i updated the bot after the server migration but it gives me a message saying it is version 1.7.6. I've double checked that i downloaded the right version so i think this is an issue. Here are some screenshots.

https://imgur.com/a/KBfsA

Edit: Wanted to add that this totally prevents the bot from working.

**Comment by spaceexploration** [comment]
Can confirm that I'm having the same issue. Tried docking on the right and bottom, no dice.

**Comment by executedlol** [comment]
Also got the same problem

**Comment by Michael12jan** [comment]
Same Problem here..

**Comment by IZEROII** [comment]
Cofirmed

**Comment by Kyanberu** [comment]
same problem.

**Comment by ExMachlna** [comment]
Same. It also resets serial number file, so even if i bypass update notif, it thinks that i'm unregistred user

**Comment by Rei-guran** [comment]
same problem.

**Comment by JohnCog** [comment]
Same problem

**Comment by JillVernus** [comment]
Same problem

**Comment by JohnCog** [comment]
Still with the same problem and already 17 hours that the bot is off.

**Comment by YumeHaru** [comment]
@Masuzu 
I've the same bug.

**Comment by JohnCog** [comment]
Bot nearly offline for 1 day.

**Comment by executedlol** [comment]
Really not going to be able to use the bot for two nights? :/

**Comment by RedMagus** [comment]
@Masuzu Considering we have to subscribe 7 days with a steep fee like this can you extend the subscription length to all users? We wouldn't be so restless if you couldn't come in and confirm how long you can fix the issue.

**Comment by JohnCog** [comment]
It is kind of bad how we are without any response or update for almost 1 day. Well I just hope we recieve a extension.

**Comment by IZEROII** [comment]
It's $5 or whatever. That's not steep, it's change. Don't care about an extension nor does he need to provide one given the TOS for this product.  What I care about is getting the issue rectified.  Masuzu sometimes does have periods where he goes AFK bc he is doing whatever he needs to be doing but normally gives a shout out that there won't be support for x period of time. 

That said fingers crossed we get an intervention soon to get this product back up and running.

**Comment by executedlol** [comment]
@IZEROII do you not know how subscriptions work? It may be change for a one time thing but it adds up after a while.

**Comment by RedMagus** [comment]
@IZEROII I think you're misunderstanding something here. Masuzu is doing a business here even if it's not exactly legal. In a business, he has responsibility to answer the customer's cries and it is OUR RIGHTS to complain, because we're PAYING him. Sure he is one man and not a god (despite god's work) but when you offer a service, you do have responsibility to keep up with it. If you don't care giving $5 a week then that's just you. The guy is collecting money from all the bot and this particular bot has steep price that is basically x2 compared to ZooeyBot and x4 compared to PokerBot. 

Don't get me wrong on the guy here. He does need to troubleshoot and keep up with 2 automated programs from scratch by himself so it's understandable he is slower to maintain both. However, since this is the most expensive bot in long term he does need to focus on this one more compared to the others.

**Comment by nobody0014** [comment]
@IZEROII  imagine, this 5 bucks per week, 4 weeks per month thats 20 bucks per month. That's more than FFXIV subscription per month, and FFXIV doesn't go down unless server maintenance. This thing has gone down for at least a day. Yea sure it's a one man project, but he does get a lot of money from this (especially from sarasa) and therefore should be maintaining a certain business standard especially if he is going to do server maintenance.

**Comment by Masuzu** [comment]
Hello, I will address this issue as soon as I can (today).
I apologize for the inconvenience.
Compensation in the form of a licence extension will be provided. @

**Comment by Masuzu** [comment]
<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr"><a href="https://twitter.com/hashtag/SarasaBot?src=hash&amp;ref_src=twsrc%5Etfw">#SarasaBot</a> A critical bug made its way in the last release. Version 1.7.8 addressed it. A one week extension was provided to all the users with a subscription, whether their licence expired or not. I apologize for the inconvenience.</p>&mdash; GBTools (@GBFPokerBot) <a href="https://twitter.com/GBFPokerBot/status/976006558587990016?ref_src=twsrc%5Etfw">March 20, 2018</a></blockquote>
