### ISSUE TITLE
NON-FUNCTIONAL, bot unable to discern chromedevtoolsdockedonright config option!!

### ISSUE THREAD

**Issue by LordShade** [Masuzu/SarasaBot#105]
on top of it saying it is still version 1.76, the bot cannot function because it is currently unable to discern this option, and instead spouts an error telling the user to check if this option has been set correctly.
True or false, docked right or at the bottom, the bot is currently non-functional as a result.

**Comment by IZEROII** [comment]
I too can confirm that Sarasa is completely non functional status post host migration/force update.  Does not recognize new version and if update is bypass you met with red error text denoting chromedevtools invalid parameters in which there is obviously no error as the .ini file has remained untouched (only the bot .exe file was updated).

**Comment by Masuzu** [comment]
Hello, I will address this issue as soon as I can (today).
I apologize for the inconvenience.
Compensation in the form of a licence extension will be provided.

**Comment by Masuzu** [comment]
<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr"><a href="https://twitter.com/hashtag/SarasaBot?src=hash&amp;ref_src=twsrc%5Etfw">#SarasaBot</a> A critical bug made its way in the last release. Version 1.7.8 addressed it. A one week extension was provided to all the users with a subscription, whether their licence expired or not. I apologize for the inconvenience.</p>&mdash; GBTools (@GBFPokerBot) <a href="https://twitter.com/GBFPokerBot/status/976006558587990016?ref_src=twsrc%5Etfw">March 20, 2018</a></blockquote>
