### ISSUE TITLE
Not detecting raids with v1.7.7

### ISSUE THREAD

**Issue by optiblast** [Masuzu/SarasaBot#106]
![vmware_2018-03-18_23-53-53](https://user-images.githubusercontent.com/35657824/37577361-1aa0bc02-2b08-11e8-89d4-d17b9bd74ab9.png)

![vmware_2018-03-18_23-54-08](https://user-images.githubusercontent.com/35657824/37577363-2029ea36-2b08-11e8-9487-b167f7d989ab.png)

**Comment by Kasenff** [comment]
Having the same problem

**Comment by Rei-guran** [comment]
same problem.

**Comment by JohnCog** [comment]
Same

**Comment by tttppp4545** [comment]
same

**Comment by bossufishu** [comment]
same..

**Comment by YumeHaru** [comment]
I hope we will get an extended period to use the bot...

**Comment by Dekiimasen** [comment]
Same issue here, hope they give us a extension for this

**Comment by Molamolaaa** [comment]
same issue

**Comment by Masuzu** [comment]
Hello, I will address this issue as soon as I can (today).
I apologize for the inconvenience.
Compensation in the form of a licence extension will be provided.

**Comment by Masuzu** [comment]
<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr"><a href="https://twitter.com/hashtag/SarasaBot?src=hash&amp;ref_src=twsrc%5Etfw">#SarasaBot</a> A critical bug made its way in the last release. Version 1.7.8 addressed it. A one week extension was provided to all the users with a subscription, whether their licence expired or not. I apologize for the inconvenience.</p>&mdash; GBTools (@GBFPokerBot) <a href="https://twitter.com/GBFPokerBot/status/976006558587990016?ref_src=twsrc%5Etfw">March 20, 2018</a></blockquote>
