### ISSUE TITLE
dear mazuzu how can i download new version?

### ISSUE THREAD

**Issue by po456asd** [Masuzu/SarasaBot#107]
in manage page download redirect to
https://github.com/Masuzu/SarasaBot/releases/tag/1.7.7

please check
https://gbtools.azurewebsites.net/SarasaBot/en/Manage

**Comment by Kyanberu** [comment]
https://github.com/Masuzu/SarasaBot/releases

**Comment by po456asd** [comment]
wow it was my stupid lol sorry.
