### ISSUE TITLE
bot loop between assist page and unclaim page

### ISSUE THREAD

**Issue by po456asd** [Masuzu/SarasaBot#109]
and it not claim finished raid. it just loop
also sometime the bot click open start menu. i don't know why.

tell me if you need video for debug.

**Comment by Masuzu** [comment]
Hello,
Please note the version incompatibility of Chrome as mentioned in the first lines of the FAQ: https://github.com/Masuzu/SarasaBot/wiki/FAQ, which causes this issue.
