### ISSUE TITLE
Crash bug present with V.1.2.0

### ISSUE THREAD

**Issue by LordShade** [Masuzu/SarasaBot#11]
With no error logs being produced but appears to be windows itself reporting that the client itself is crashing. Seems to get to within 1~4 raids joined before the client itself crashes. This is happening however constantly after moving to the summon selection screen of the next raid, possibly related to that? Or maybe something to do with BP refilling? Theres no programs running on this laptop of mine apart from Chrome so it shouldn't be something in the background.

heres a picture if it helps out at all : https://puu.sh/yzugj/b6d057fc4e.png

**Comment by lemonphi** [comment]
Am experiencing the same issue.

**Comment by Masuzu** [comment]
Hi,
I will look into it later in the day.

**Comment by Masuzu** [comment]
I believe it happens only if the summon page takes too long to load.

**Comment by LordShade** [comment]
then some kind of mitigation must be put into place to avoid it since not everyone is running super internet or super computers. Bot has been unusable since the update for me.

**Comment by Masuzu** [comment]
Tentative patch v1.2.1 https://poker-bot.azurewebsites.net/SarasaBot/en/Home/PatchNotes#1-2-1

**Comment by LordShade** [comment]
was crashing with the default config file, however I changed a few of the settings around (mainly the delay ms between mouse up and down presses) and it seemed to have fixed itself (weird)

Maybe it was an issue with how fast the computer was processing the clicks and causing windows to throw a crash error. Since whenever it crashed no crashlog was presented or any changes in the cmd window.

**Comment by Masuzu** [comment]
Hi,

Please provide a full screenshot showing the last lines in the log of the console (some debug messages were adde there). I can't understand what the issue is otherwise.

**Comment by LordShade** [comment]
[https://puu.sh/yAzSF/b73772339a.png](url)

**Comment by Masuzu** [comment]
Thank you, will follow up in https://github.com/Masuzu/SarasaBot/issues/14
