### ISSUE TITLE
Can't download the new version of sarasabot

### ISSUE THREAD

**Issue by cobeng13** [Masuzu/SarasaBot#110]
![image](https://user-images.githubusercontent.com/19832551/37652612-6878d64e-2c7f-11e8-92e0-f0fff7382ec0.png)

Can't download the zip file, thanks

**Comment by Rei-guran** [comment]
Also. There is also no extension written on Twitter.

**Comment by Dekiimasen** [comment]
https://github.com/Masuzu/SarasaBot/releases download 1.7.8 through here

**Comment by cobeng13** [comment]
@Dekiimasen Thank you

**Comment by Masuzu** [comment]
The link was fixed.
The extension took the form of an additional 7 days, not a renewal.
