### ISSUE TITLE
No Summon could be found

### ISSUE THREAD

**Issue by NaoiKR** [Masuzu/SarasaBot#116]
I buyed SarasaBot license today, but can't make it work.

Basically when Sarasa tries to connect to a raid, I receive a "No summon could be found" message on it and an annoying sound (the captcha_notification.mp3). Tried several times but still nothing.

Zooey bot works fine on my computer. Already tested it before.

**Comment by po456asd** [comment]
have you use chromium?

**Comment by Masuzu** [comment]
Hello,
It was a Chromium issue indeed.
Now Chrome version is checked beforehand, avoiding this kind of issues.
