### ISSUE TITLE
Cannot join raid

### ISSUE THREAD

**Issue by Altariarite** [Masuzu/SarasaBot#117]
Cannot join raid, the bot keep refreshing without showing the number of raids to join. ( with DisplayRaids = true)
I set up my RaidsToTrack exactly as following
`RaidsToTrack=Lvl 75 Celeste Omega,Lv75 セレスト・マグナ,Lvl 75 Luminiera Omega,Lv75 シュヴァリエ・マグナ
`
I've also experimented with tracking only one raid, but neither would work even if a raid meets all the criteria.
I've updated my chrome, disabled auto completion, and strictly followed all the prerequisites.

Please help.

**Comment by Masuzu** [comment]
Hello,
If you have no tweets appearing:
![image](https://user-images.githubusercontent.com/5464705/37866597-1ae7507a-2f8d-11e8-905c-6dc12c220927.png)
it looks like a Twitter issue on your side.
I know that in China there may be some issues retrieving tweets.

**Comment by Zir1984** [comment]
Im having the same issue, i been using sarasabot since release and this is the first time this happened
![image](https://user-images.githubusercontent.com/28830947/38339111-fc3ba590-3842-11e8-9e92-984e8f165075.png)

**Comment by Masuzu** [comment]
Transient Twitter issues can lead into this situation.
