### ISSUE TITLE
Select target bug?

### ISSUE THREAD

**Issue by YumeHaru** [Masuzu/SarasaBot#119]
Hi,

I'm trying to write a script for Yggdrassil impossible and as you know we need to kill the add first. I'm able to code the target selection to select the add but a few "bugs" are happening when I use that command:

- my dark fencer doesn't use skill on Ygg, it doesn't switch to it when I use that command > if enemy_2.charge_diamonds
- when the add die the bot get stuck and try to select it again instead of ignoring it and switch to Ygg like the Lua script guide said.

I don't know if it's a bug or if I made a mistake in my script...

```
Summon(1)
Summon(2)
Summon(5)

-- [[Disable charge attack by default]] --
if character_1.charge_gauge >= 100 then
  EnableChargeAttack()
else
  DisableChargeAttack()
end

-- [[Battle]] --
SelectTarget(1)
characters["Main character"]:UseSkill(2)
characters["Petra"]:UseSkill(2)
characters["Petra"]:UseSkill(3)
characters["Lancelot"]:UseSkill(1)
characters["Lancelot"]:UseSkill(2)
characters["Lancelot"]:UseSkill(3)
characters["Gawain"]:UseSkill(1)
characters["Main character"]:UseSkill(4)

if enemy_2.charge_diamonds == 1 then
characters["Main character"]:UseSkill(3)
characters["Main character"]:UseSkill(1)
end

if enemy_2.charge_diamonds == 2 then
characters["Gawain"]:UseSkill(3)
Summon(3)
end

if turn == 6 then
Summon(6)
end
```

**Comment by YumeHaru** [comment]
I removed the SelectTarget(1) since game target it by default but I still don't know why my Dark Fencer won't use his skill on Ygg but stay instead on the add.

**Comment by Masuzu** [comment]
Hello,
Enemy positions are not intuitively what you think you could be. Enemy 1 is the enemy whose HP bar is on the far left.
Enemy 3 the one whose HP bar is on the far right.
