### ISSUE TITLE
Shares the same id/manifest as Zooey?

### ISSUE THREAD

**Issue by silverraine** [Masuzu/SarasaBot#12]
Since I have both Zooey and Sarasa, I noticed that upon installation of the Chrome extension Sarasa has replaced the Zooey extension instead of being a separate one. Is this intended?

**Comment by Masuzu** [comment]
This is not an issue.

**Comment by Masuzu** [comment]
Addressed in
https://poker-bot.azurewebsites.net/SarasaBot/en/Home/PatchNotes#1-2-1
