### ISSUE TITLE
Sarasabot stuck after combat mode active

### ISSUE THREAD

**Issue by shiraseo** [Masuzu/SarasaBot#120]
I bought the bot yesterday, and till now it keeps getting stuck after the party join the battle and combat mode active is appearing in sarasabot.exe. After the 'combat mode active' then whats aooear on the sarasabot.exe is "new page loaded: <games raid urls>
And sometimes, the bot is iddle after the check when it first started and never told me to go to the quest screen. Please help me to solve the problems, Thank you.

**Comment by shiraseo** [comment]
For more information, I am using the latest version of chromium. Ver 67.0.3379.0
And using sarasabot v1.7.10

**Comment by Masuzu** [comment]
Hello,
Please make sure to close all your Chrome Devtools windows beforehand. If you are already on the quest page after starting the extension, press F5 or go back to your Home screen then click again on the Quest menu. Closing and reopening the browser can also unlock the situation in cases where you forcibly stop it and rerun it.
If you do not seem to perform any action in a battle, make sure to check the Lua script that you are using: https://github.com/Masuzu/SarasaBot/wiki/Lua-scripts
The one provided by default will use a skill then look for other raids to join (unless there are 3 ongoing raids already)
