### ISSUE TITLE
I will not go to pick up quests punished.

### ISSUE THREAD

**Issue by rarudo357** [Masuzu/SarasaBot#122]
I am writing using a translation site.
Although it is as the title is, I will not receive the reward of the raid which the suppression is completed.
Therefore, once a certain number of quests are completed, it will be impossible to participate in the raid any more.
If you can understand the cause, please tell me.

**Comment by ExMachlna** [comment]
Was going to post the same. So, in proper english, bot fails to claim a raid rewards. it goes to the pending raids page, does nothing and returns to the join raid page. After a certain number of completed raids it will just cycle like that endlessly, being unable to join another one. Win10, 1366x768, laptop, google chrome 65.0.3325.181 x64

**Comment by ptfff** [comment]
getting the same issue too, I'm having to watch it and keep on top of claiming quest rewards.

**Comment by Masuzu** [comment]
Hello,
Tgis is caused by a Chrome version issue: https://github.com/Masuzu/SarasaBot/issues/124
