### ISSUE TITLE
sarasa bot failed in reading every server respond in the lastest patch

### ISSUE THREAD

**Issue by Keylein** [Masuzu/SarasaBot#123]
After upgrading the patch to the lastest patch,sarasa bot cant read every message from the server and causing the program itself to recast the skills and try to re-summon every single time. This also cause the bot ignore every wait time,like full burst or something.

**Comment by Masuzu** [comment]
Hello,
If you have constant "No response received after using a skill", this is caused by a Chrome version issue: https://github.com/Masuzu/SarasaBot/issues/124
