### ISSUE TITLE
Won't Claim Raids

### ISSUE THREAD

**Issue by Bakamoto** [Masuzu/SarasaBot#125]
Haven't used bot in a bit and nothing was wrong previously, using the same ini file while updating everything else, but the bot won't claim the completed raids in the pending raid screen. It would just loop between the pending page doing nothing and failing to join raids since there is a full page of unclaimed raids. Any idea what happened ?

**Comment by Molamolaaa** [comment]
same

**Comment by krypticsalt** [comment]
Confirming that it won't claim raids. also seems to not be able to recognize a skill has been used. the game will use something like treasure hunt correctly but sarasa will give the error message due to lack of response from gbf server.

**Comment by Bakamoto** [comment]
Yeah that happens to me too ^ The skill has already been clicked or sometimes it's not registering and sarasa will give that same message.

**Comment by po456asd** [comment]
change your browser into chromium or something that compatible.  Google chrome version 65.xxx cant use the bot.
