### ISSUE TITLE
Not working after latest patch

### ISSUE THREAD

**Issue by lolipirate** [Masuzu/SarasaBot#126]
Hello there.
I just upgraded to the last patch and suddenly it does not work anymore. It picks up the raids, but cannot do anything with them. It registers the window and me clicking on the extension, but that's it. It also registers me navigating to quest menu, where it start calibrating but never starts working.

**Comment by lolipirate** [comment]
https://i.imgur.com/KVB98nb.png
https://i.imgur.com/w2gsnIS.png

**Comment by lolipirate** [comment]
Alright, I refuse to pay for anything that doesn't work half the times I need it. You finally fixed this bug in the newest version, but now it won't attack.

**Comment by po456asd** [comment]
1. did you open network tab?
2. did you open it and navigate to quest?
3. did you set network dock to the one you choose?
4. did you use chrome that not compatible?
5. did you try to change the game into chromium?
6. please install all font into your windows. you can copy them from your main pc to that. it doesn't matter what os you use / ex. you can copy all font from win 10 to win 7

**Comment by lolipirate** [comment]
1, 2, 3. Yes of course, I had it work before, I used exact same procedure this time. 
4, 5. I use the chromium version the owner told us to use. 
6. Fonts got nothing to do with this. Like I said, it worked before, now it doesn't.

**Comment by po456asd** [comment]
-it wont attack

please paste lua script that you use here

**Comment by lolipirate** [comment]
`if turn == 1 then
  character_3:UseSkill(2)
  character_3:UseSkill(3)
  character_3:UseSkill(1)
end
	TerminateBattle()`

**Comment by lolipirate** [comment]
if turn == 1 then
  character_3:UseSkill(2)
  character_3:UseSkill(3)
  character_3:UseSkill(1)
end
	TerminateBattle()

**Comment by lolipirate** [comment]
Without the support of the creator, I fixed the problem myself, but now the next problem starts. It cannot move on when receiving the message: "This battle has ended. The foe was defeated."

**Comment by Masuzu** [comment]
Hello,
I added to my backlog list the review of battle end detection and will check it this week end.

**Comment by Masuzu** [comment]
This particular case of battle ending was addressed in v1.8.0
https://gbtools.azurewebsites.net/SarasaBot/en/Home/PatchNotes#1-8-0
