### ISSUE TITLE
Some issues that make Sarasa stuck

### ISSUE THREAD

**Issue by water000qazzaqzxccxz** [Masuzu/SarasaBot#127]
Sorry for my bad English
I think I get some problems that would make bot stuck but I don't really know what cause it
I just describe  the situation
it is similar to #94 
I usually set refresh() after summon in order to earn some time
but sometimes  after refresh() the page gets back and the battle just ends
then the bot gets stuck  even the next button appears
I guess because the bot hasn't pushed the attack button
however , it looks fine if  the page refreshing is caused by response time delay
 
the other problem is that the devtool would be closed , but I don't know the reason
it is rare case

**Comment by LordShade** [comment]
adding onto devtools randomly being closed by sarasa, she'll crash if this happens.
she also sometimes clicked other sections of the devtool, maybe like source which is next to the network tab, and bug out if this happens too.

**Comment by i-Grey** [comment]
Same issue in case #94 happens with me too.
Refresh by hand can't solve this issue. Sarasa tried to press BACK button only and didn't do anything such as refresh or push the OK botton on 'This battle has ended' screen.

Is there anyway to fix this temporary or just wait until the latest updated come.

**Comment by Masuzu** [comment]
Hello,
I take note about the "post manual Refresh" issue which can cause Sarasa to be stuck when a battle ends.
@LordShade This is not supposed to happen at all as long as your ribbon looks like this (the tab order does not matter)
![image](https://user-images.githubusercontent.com/5464705/38162091-8ccaed7a-34db-11e8-969f-fab30cfdccaa.png)

**Comment by Masuzu** [comment]
Improved battle end detection was added to cover the case described here along with other improvements when the `Refresh` command is used in Lua scripts.
https://gbtools.azurewebsites.net/SarasaBot/en/Home/PatchNotes#1-8-0
