### ISSUE TITLE
refreshing really fast on raids page

### ISSUE THREAD

**Issue by zannettsama** [Masuzu/SarasaBot#129]
not sure what I did but I was tweaking the parameters aroundn a bit and now it's refreshing really fast on raid page?

**Comment by Masuzu** [comment]
Hello,
I will add a new parameter to control this in the next release.

**Comment by Masuzu** [comment]
The refresh frequency is now configurable: https://gbtools.azurewebsites.net/SarasaBot/en/Home/PatchNotes#1-8-0
