### ISSUE TITLE
[Request] Push bullet notification

### ISSUE THREAD

**Issue by po456asd** [Masuzu/SarasaBot#130]
maybe after every raids end and if collected reward and got ssr or something also maybe push bullet when got captcha

in setting i think it will have just switch on-off this feature and pushbullet_token i think

reference : https://autohotkey.com/boards/viewtopic.php?t=4842

**Comment by po456asd** [comment]
example ini setting
EnablePushBullet=true/false
PushBulletToken=**************

EnableNotificationWhenGotCaptcha=true/false

EnableNotificationWhenClaimReward=true/false
;this one maybe counting up how many raid has been done.
;maybe

;finished=+1 

;when claim reward and counting up. when notification trigger we use like
;PB_Message := "Finished Raid number = "%finished%"."

**Comment by Masuzu** [comment]
Hello,
That is a good idea. I am not sure however if I want to dedicate time for this.
