### ISSUE TITLE
Bot is not working :(

### ISSUE THREAD

**Issue by blazex21** [Masuzu/SarasaBot#131]
i've used the bot many times before but since the latest patch came out i have not been able to use the bot. i do not receive the message to "proceed to quest tab" 
![untitled](https://user-images.githubusercontent.com/37790115/37887904-6f986464-3092-11e8-8017-3a134cb4e023.png)
i've made sure the devtools are docked on the right as well as it being set to true in the config. im not sure what im missing.

**Comment by po456asd** [comment]
have you try go to quest tab yet? how is it?

**Comment by Masuzu** [comment]
Hello,
Please refer to https://github.com/Masuzu/SarasaBot/wiki/Getting-started step 8
