### ISSUE TITLE
Bot keeps clicking windows button

### ISSUE THREAD

**Issue by DarkenShade** [Masuzu/SarasaBot#132]
bot clicks windows button when selecting summon every 3 to 5 raids which causes the  bot jam up because the window isnt selected.

**Comment by DarkenShade** [comment]
also if i move the task bar to the side of my screen it instead clicks the bottom side bar button opening another tab to mobage games

**Comment by po456asd** [comment]
in setting file. check network dock setting.

**Comment by Masuzu** [comment]
Hello,
Please check https://github.com/Masuzu/SarasaBot/wiki/Getting-started step 5.
