### ISSUE TITLE
Sarasa bot isnt fetching raids

### ISSUE THREAD

**Issue by iSDestiny** [Masuzu/SarasaBot#133]
My bot stopped fetching raids, this issue started happening a couple of minutes to an hour ago. 
![image](https://user-images.githubusercontent.com/32033119/38051603-a397575a-3283-11e8-8f90-15e66ea1a8f7.png)
Anyone know what could be the problem?

**Comment by shiraseo** [comment]
I have the same issue. My bot stopped tracking the raids and it occured about 10 minutes ago. Its working before that without problems.

**Comment by celefarming** [comment]
Just bought the bot and have been trying to get it to work, but it seems unusable most of the time. I often get "there are 0 ongoing raids" and the bot just refreshes in a loop.

**Comment by poliwhirlfan61** [comment]
Hello, also reporting this issue, ive regenerated my applications keys just to be sure it wasn't on the twitter end but the bot still seems to not be fetching raids.

**Comment by celefarming** [comment]
@poliwhirlfan61 Do you think that the issue is with Twitter and not the bot?

**Comment by poliwhirlfan61** [comment]
![image](https://user-images.githubusercontent.com/35543465/38054590-2b22604e-3323-11e8-818b-586a99ffc9a6.png)

Yes twitter.

**Comment by Masuzu** [comment]
Hello,
Transient Twitter issues can't be helped.
