### ISSUE TITLE
have trouble obtaining Twitter credentials

### ISSUE THREAD

**Issue by wsadadsw** [Masuzu/SarasaBot#134]
Hi, I got stuck in creating a new Twitter app. I logged in my Twitter account and navigate to https://apps.twitter.com/app/new to create a new Twitter app but It continues saying "Your application has been created. Please take a moment to review and adjust your application's settings" and "You don’t currently have any Twitter Apps" after I send the form.  I have no idea about what's going on.

**Comment by Masuzu** [comment]
Hello,
Simply go to https://apps.twitter.com/ to check your newly created application.
