### ISSUE TITLE
Paused in debugger

### ISSUE THREAD

**Issue by Ramkm77** [Masuzu/SarasaBot#138]
Hi . This issue started few days ago . Not sure what's the cause . [Please](url) help
Usually start poping  after like 50 raids or less
![20180404_191032](https://user-images.githubusercontent.com/30638021/38316562-12442490-383c-11e8-95ac-afd49d87d4a0.jpg)

And I tried to use incognito version but seem sarasa not compitable with it ??

**Comment by Masuzu** [comment]
Hello,
Please make sure to disable this parameter:
![image](https://user-images.githubusercontent.com/5464705/38386672-a37e9678-3915-11e8-958d-4517062c0a15.png)
