### ISSUE TITLE
bot not hitting

### ISSUE THREAD

**Issue by kisame21** [Masuzu/SarasaBot#139]
the bot works and joins raid all fine but it doesnt do anything when in raid. it doesnt hit or use skill or anything. it just refreshes either to another raid or to raid tab and repeats. mind telling how to fix this? @Masuzu

**Comment by Zir1984** [comment]
Did you set viramate to true? if so make sure the keyboard hotkeys is enabled

**Comment by kisame21** [comment]
i have. and i tried with script and without script. still doesnt work no matter what. been trying for 2 days now. still not working. is there an older version which is working so i can use that instead? i havent even get to use the bot since i bought it which is kinda annoying.

**Comment by shock1601** [comment]
I used to got this too, fixed by increasing the MaxInactivityPeriodBeforeLeavingTheRaidInMs in Combat tag

**Comment by kisame21** [comment]
May I know how long did you increase it? And from what I notice it just doesn't run the script to either hit attack or any specific.lua script. It states enter combat mode and once raid loads it terminates the raid

**Comment by kisame21** [comment]
(update) for some reason the bot started working properly.

**Comment by shock1601** [comment]
Actually I increased it to 30000 (30s). I think its about connection problem so if the parameter is low, the bot will retreat from the raid because inactivity

**Comment by kisame21** [comment]
Yea i also increased mine to 30000 iirc. And it's working again. I guess that solves it for now. Back to leeching magna2. Thanks for help

**Comment by Masuzu** [comment]
Hello,
Thank you for reporting this, I will look into it and review the `MaxInactivityPeriodBeforeLeavingTheRaidInMs` parameter.

**Comment by Masuzu** [comment]
I can confirm that the parameter works as intended but may have a default value set too low depending on the initial boss animation when entering the raid and ping, these 2 being the main factors.
https://gbtools.azurewebsites.net/SarasaBot/en/Home/PatchNotes#1-8-2
