### ISSUE TITLE
This battle has ended popup disrupting the bot.

### ISSUE THREAD

**Issue by zooeyjapan** [Masuzu/SarasaBot#141]
Hi,

(Re https://github.com/Masuzu/SarasaBot/issues/94 ) 

This still happens frequently (when not using viramate hotkeys), 
and the battle ends before the user-script is completed. 
ie lunalu -> sarasa 2 actions script. If the raid dies while in the skill menu and clicking the skill icon -> pop up appears -> bot keeps trying to click back button instead of noticing the popup. 

When using hotkeys I didn't encounter the problem, but there is alot of misinformation about the hotkey functionalities/detection.

Ideally if would simply refresh the raid if it notices a skill or next line in the lua script is not being executed 
after a certain amount of time.

**Comment by shock1601** [comment]
I have this problem too. It can be improved by increasing the MinimumRemainingBossHpPercentage or/and decrease MaxNumPlayersInRaid but it is not optimized. I hope the bot will do smth like refresh the page or turn off the pop-up instead of continuously clicking the Back button

**Comment by Masuzu** [comment]
Hello,
I took note of the issue. It is entirely specific to not using Viramate shortcuts indeed.

**Comment by robowhip** [comment]
Apart from viramate hotkeys, is there a lua script that might help avoid this bug or the best we can do is wait and hope for a fix? I have been using sarasa for a day and it has been great but it gets hindered by this one thing way too often. 

I have tried running an auto-refresh extension simultaneously which has actually managed to get out of that situation with the right timing but instead sometimes messes up the turn counter or stops sarasa altogether. Also, caused sarasa to be stuck in combat mode on few occasions, unable to restart the raid search... 

If anyone has a real solution, it would help greatly!

**Comment by shock1601** [comment]
It seems not just the battle has ended popup disrupting the bot, but also any kind of notification or animation such as boss transform or boss is in overdrive/break state also make the mouse cursor continuously just MOVE AROUND the BACK button WITHOUT CLICKING it. The debug message just show the red message "No response received..." 1 time only and then nothing more was shown.
![e1](https://user-images.githubusercontent.com/37844825/38883853-099f0c02-42a9-11e8-8faa-c91cfccc1635.png)
In this case, when the battle is still on, I solved it by manually pressing ESC and the bot back to work normally. But if the bot was disrupted by The battle has ended popup, the ESC didn't work and I have to Manually refresh the page by pressing F5(debug message shown in next pic)
![e2](https://user-images.githubusercontent.com/37844825/38883807-ed6f06c2-42a8-11e8-8764-1e386a660900.PNG)
P/s: I dont use Viramate

**Comment by Masuzu** [comment]
Hello,
All I can say for now is that you should really consider using Viramate shortcuts for public raids.
