### ISSUE TITLE
How to avoid "Failed to select characterUse skill at..." msg?

### ISSUE THREAD

**Issue by Nassy1121** [Masuzu/SarasaBot#145]
I often faced with below message and sarasa bot was stacked.
> Failed to select characterUse skill at position 2
It happens when shiva and greemnil are transforming.( Insert some wait )

Please let me know I can set or extend any wait time value?

Thanks,
[logs.txt](https://github.com/Masuzu/SarasaBot/files/1910186/logs.txt)

**Comment by Masuzu** [comment]
Hello,
You should use [Custom user variables](https://github.com/Masuzu/ZooeyBot/wiki/Lua-scripts#custom-user-variables) and do something similar to:
```
if not booleans["transformed"]:
  if enemy_1.hp <= 50:
    booleans["transformed"] = true
    Wait(XXXX)
  end
```
