### ISSUE TITLE
Bot seems unable to detect ongoing raids after some time.

### ISSUE THREAD

**Issue by ExtantLily** [Masuzu/SarasaBot#148]
After leaving the bot running for about an hour, it starts looping the ongoing raids page and displaying this message in the console: 
![screenshot_23](https://user-images.githubusercontent.com/32333321/38825754-499c910e-41e0-11e8-87d9-5421a3ceef1f.png)

I would ordinarily chalk it down to there being no ongoing raids, but given the normal frequency of raids being read, this seems unlikely.

**Comment by Masuzu** [comment]
Hello,
Sometimes Twitter can have an issue and as a result, raids are not picked up anymore.
It seems you ran into this issue.
