### ISSUE TITLE
Ongoing raid refresh frequency line does not work

### ISSUE THREAD

**Issue by robowhip** [Masuzu/SarasaBot#149]
As stated above, the line  `OngoingRaidsCheckFrequencyInSeconds` does not work. Instead, Sarasa seems to refresh raids based on `MaxResponseDelayInMs` value. The trouble with the latter is, the same value is being used in combat mode to determine server response and because of a certain other issue I need this to be at over 45000ms, leaving Sarasa to only attempt joining a raid every 45 seconds, which, as you might imagine, is far from ideal. 

Some additional information:

Windows 7 
Chromium Version 67.0.3386.0 (Official Build) (64-bit)
Sarasa-Bot 1.8.3 
No Viramate.

Thanks

**Comment by Masuzu** [comment]
Hello,
Thank you for reporting this, I identified an issue indeed.

**Comment by Masuzu** [comment]
Hello,
This is now addressed in v1.8.4
