### ISSUE TITLE
Bot gets stuck after awhile

### ISSUE THREAD

**Issue by violafayde** [Masuzu/SarasaBot#15]
Hi, when i run the bot on Luminiera Omega, it goes without issues for a certain period of time. However, after awhile it starts to try to join battles but the dialog box 'This raid battle has ended. Check your pending battles.' keeps appearing. It only works again if i restart the bot. I'm not sure what causes this problem.

**Comment by Masuzu** [comment]
Hi,
On which screen does the dialog box 'This raid battle has ended. Check your pending battles.' keeps appearing? Summon selection page? Other page?

**Comment by violafayde** [comment]
It appears on the raid selection page.

**Comment by violafayde** [comment]
update: this dialog box happens when the bot's log repeated shows 'Combat mode active' instead of trying to join a new raid.
