### ISSUE TITLE
SarasaBot.exe stopped working

### ISSUE THREAD

**Issue by shock1601** [Masuzu/SarasaBot#151]
I still got errors such as mentioned in #141 and #143 since started using Sarasa Bot for a week, but after v.1.8.3 update, this is the problem I usually got
![e3](https://user-images.githubusercontent.com/37844825/38942779-b429808c-436a-11e8-8933-f53edef84984.png)
It seems really similar to #141 , just different in timing which in #141 is when selecting a skill and in this case was when selecting character...
Im using Chromium Version 67.0.3366.0

**Comment by Masuzu** [comment]
Hello,
All I can say for now is that you should really consider using Viramate for public raids.

**Comment by LordShade** [comment]
same issue here except its after 15minutes of usage, seems to crash consistently. No explanation given apart from the fact its when trying to join a raid.

**Comment by Masuzu** [comment]
This is now mitigated in v1.9.0
