### ISSUE TITLE
Nothing's happening.

### ISSUE THREAD

**Issue by Jotajega** [Masuzu/SarasaBot#153]
Okay, so I did the whole thing, I had many problems at first, but I carved the .ini text to perfection according to the standards of the installation guide, perquisites, and getting started. 

I'm not too sure what to do from here. 
![screenshot_14](https://user-images.githubusercontent.com/38640746/39105809-4be44eb8-468e-11e8-865e-be1bbebc170e.png)

It tells me to set the value of the tool dock to true or false, depending if it's on the right or the bottom.
There is no need to remind me how this works, because I am pretty certain that my dock is on the right, and the value is set to "true".

Then it tells me that everything is ready and asks me to proceed to the quest menu, which I do.
But really, nothing's going on, the program just keeps scanning raids off tweetdeck forever.

I have a idea that I'm just being a ignorant blind noob because this is my first time downloading notepad++, and I have never meddled with scripts, or any type of codes before.

Even if you have a tiny idea what this could be, please let me know, it's been 2 days since I purchased the licence and I'm wasting it. Thank you for reading.

Best regards

**Comment by Jotajega** [comment]
Also, if there is a possibility of getting contacted on discord for live chatting and getting this issue fixed as soon as possible, please add me Jotarome#3769

**Comment by Vatar** [comment]
Hello, have you made sure that you put the game size to medium? You can click the 2 blue dots at the bottom for that:

“Size   .     ..   ...   Full”

Moreover, you have to disable hardware acceleration in your chrome settings.

**Comment by Jotajega** [comment]
Thanks, I'll try it out when I get home.

**Comment by Jotajega** [comment]
Alright, that fixed it, thanks a bunch.
