### ISSUE TITLE
Sarasabot not working after renewing subscription

### ISSUE THREAD

**Issue by dodinhtrung97** [Masuzu/SarasaBot#154]
Ever since I renewed my subscription for sarasabot (yesterday) it's been stuck in a 0 raid found loop and failed and find any raid even though I've set the parameter DisplayRaids to true. This was always a problem before but it's always fixed itself after a certain amount of time.
If there's no way to fix this, I want to request a refund.
![untitled](https://user-images.githubusercontent.com/16840128/39321115-4af88800-49b0-11e8-968c-4e64ce097d87.png)

**Comment by Masuzu** [comment]
Hello,
It may have been an issue with Twitter.
My feed of raids works fine right now as I am typing.
