### ISSUE TITLE
why does my treasuremode can't detect scrips ?

### ISSUE THREAD

**Issue by gary173** [Masuzu/SarasaBot#156]
I can't use skill
Scrips can work normally in event mode
In treasureeventmode ,bot can choose stage and summon normally but bot will only attack
Would anybody help me ? 
![2](https://user-images.githubusercontent.com/37240918/39388685-88914a76-4ab4-11e8-968e-9e01d0f8ab60.PNG)

![1](https://user-images.githubusercontent.com/37240918/39388628-1c8c09ba-4ab4-11e8-966a-8ea6039f95f7.PNG)

**Comment by ariaanaa** [comment]
treasureEventModeScript=Scripts/95hell.lua remove "="

**Comment by Masuzu** [comment]
Thank you @ariaanaa
