### ISSUE TITLE
Can't pick element in support summons

### ISSUE THREAD

**Issue by iSDestiny** [Masuzu/SarasaBot#158]
https://i.gyazo.com/4333b30ffe2d306f5c99564f0fca1422.mp4

Video above shows my problem. Anyone having this problem? Not sure if it is something wrong with the bot or with chromium. This happens randomly and screws with the bot.

**Comment by Masuzu** [comment]
Hello,
You may be using one of Chromium build which has some issues. For instance, all the Chromium v67 builds are not compatible.
The official Chrome build Version 66.0.3359.139 works fine.
