### ISSUE TITLE
Is there a dev plan for the UI of the bot?

### ISSUE THREAD

**Issue by masakacj** [Masuzu/SarasaBot#159]
Great tools! Highly customized configuration makes it capable for every single usage situation.
But keep editing the config is also a little annoying.
So i just wanna ask if there is a plan for the Bot UI design, which would make it much easier to config the modes and values

**Comment by Masuzu** [comment]
Thank you for the feedback.
I have no plans in the foreseeable future to add such features, but user versioning is already somehow possible, simply by keeping separate copies of different configuration files.
