### ISSUE TITLE
Enhancement - Fast Refresh

### ISSUE THREAD

**Issue by appleloli** [Masuzu/SarasaBot#162]
Hello with the advent of magna2 and the amount of time we have to attack in a raid, i was wondering if are you able to implement fast refresh which is basically going back then forward on the webpage.

**Comment by Masuzu** [comment]
Hello,
I am not sure how it would improve things compared to reloading the page? The caching of the elements of the page which can be cached by the browser happen whether you press the back button and then forward, or reload the page.

**Comment by appleloli** [comment]
To be honest i don't know the specifics but it certainly loads faster for me, there are other bugs associated with it like phalanx or other effects not showing up, but that's beside the point when going for speed, i can show you an example if need be.

**Comment by Masuzu** [comment]
Thank you for the time recoring the video!
Interesting, I could do something about it.
