### ISSUE TITLE
unable to use skills after updating to 1.9.1

### ISSUE THREAD

**Issue by yurihanabira** [Masuzu/SarasaBot#164]
After updating to 1.9.1, Sarasa seems to be unable to use skills anymore. Mouse doesn't move in combat, nothing happens, it just loops the same error then eventually just wanpans.

https://imgur.com/a/n0dTeyd

Reverting to 1.8.5 is my current solution.

Currently using Chromium Version 63.0.3225.0 (Developer Build) (64-bit)

**Comment by Masuzu** [comment]
I apologize for the inconvenience. A fix is on its way as soon as possible.
https://github.com/Masuzu/ZooeyBot/issues/790

**Comment by Masuzu** [comment]
This is now addressed in v1.9.2
