### ISSUE TITLE
Bot wont click 4th character to use skill

### ISSUE THREAD

**Issue by zappky** [Masuzu/SarasaBot#166]
I tried to swap around the 4th character to see if it is my script having problem or the bot having problem.
In the end, no matter which char i put at 4th spot, the bot just cannot click it. 
Giving *red text* Unable to select character *blue text* Select character at position 4

Version 1.9.2

**Comment by Masuzu** [comment]
Hello,
Thank you for reporting this issue!
This is now addressed in v1.9.3.
