### ISSUE TITLE
Bot Stopped at the result page

### ISSUE THREAD

**Issue by nobody0014** [Masuzu/SarasaBot#168]
Here it stopped at this, I'm not sure what's causing it but it should happen when the raid dies before you are able to attack. Also if it is possible, it would be nice to know what version of chromium the dev is using so that we dont need to have as many issues.
![screen shot 2561-05-15 at 8 53 45 am](https://user-images.githubusercontent.com/13681469/40032290-b7136e94-581d-11e8-9e18-9478984835c2.png)
![screen shot 2561-05-15 at 8 54 33 am](https://user-images.githubusercontent.com/13681469/40032291-b7ee53ce-581d-11e8-8894-cde6ee85dd03.png)

**Comment by nobody0014** [comment]
It just stuck, happened again just now

**Comment by Masuzu** [comment]
This is now addressed in v1.9.5
