### ISSUE TITLE
Stuck at finding raids

### ISSUE THREAD

**Issue by nobody0014** [Masuzu/SarasaBot#17]
So what happen is after running the bot for awhile, the bot is unable to find any new raids even though there're new raids popping up.

**Comment by nobody0014** [comment]
<img width="705" alt="screen shot 2017-12-07 at 12 19 00 pm" src="https://user-images.githubusercontent.com/13681469/33699992-1070dd8e-db49-11e7-93cc-75b9cd28fbed.png">

**Comment by Masuzu** [comment]
Hi,
I have my guess about what the cause is. I will fix this.

**Comment by Masuzu** [comment]
Mitigation was added in v1.3.0 https://poker-bot.azurewebsites.net/SarasaBot/en/Home/PatchNotes#1-3-0

**Comment by nobody0014** [comment]
thank, there's another bug but ill post it in another issue, although it's just a minor bug

**Comment by nobody0014** [comment]
still having issues, is it in some setting?
<img width="652" alt="screen shot 2017-12-08 at 1 57 33 pm" src="https://user-images.githubusercontent.com/13681469/33754667-e95afd56-dc1f-11e7-8262-751020cd05ac.png">
<img width="856" alt="screen shot 2017-12-08 at 1 55 48 pm" src="https://user-images.githubusercontent.com/13681469/33754668-e9a88d14-dc1f-11e7-8740-bad7858b9a82.png">

**Comment by Masuzu** [comment]
This is not an issue.
It is just informational messages.
Some raids already ended/are full by the time you try to join them hence the failed to join the raid message.
