### ISSUE TITLE
Invalid Twitter Credentials

### ISSUE THREAD

**Issue by finaljusticemh** [Masuzu/SarasaBot#171]
Locale is EN
I've made sure there were no spaces between the keys/tokens
Tried UTf-8 with and without BOM
I even updated my local PC time
Not sure what the issue is.

**Comment by Miyoumu** [comment]
@Masuzu I am having the same issue? Perhaps an issue with the bot?

**Comment by Masuzu** [comment]
I can confirm that at the release time of v1.9.4 there were no issue.
The only possible explanation was a temporary Twitter API shortage.
As I type right now the raids are retrieved properly (8:26 PM GMT+0).
![image](https://user-images.githubusercontent.com/5464705/40283334-cb6b9048-5c7c-11e8-9003-f72254516885.png)

**Comment by Masuzu** [comment]
There used to be a bug which would cause the invalid Twitter credential message to appear if in your pinned tweets some words would be present but this exact same issue was addressed in v1.9.4.
