### ISSUE TITLE
Failed to load raid

### ISSUE THREAD

**Issue by YumeHaru** [Masuzu/SarasaBot#172]
I've the same issue as this person https://github.com/Masuzu/SarasaBot/issues/167
Bot worked fine yesterday but today it always fail to join raid when it end the battle.

I've the last version of bot and Chronium.

**Comment by Masuzu** [comment]
Hello,
I can join raid fine at this period of the day (which is also a much less active hour). This is simply a Twitter issue, which can happen sometimes.
