### ISSUE TITLE
Bot still gets stuck at end of raid in 1.9.5

### ISSUE THREAD

**Issue by CorrinKrow** [Masuzu/SarasaBot#173]
![image](https://user-images.githubusercontent.com/36133340/40292455-5c9b2f06-5cc3-11e8-928e-b15d055f7fa5.png)

I know the last patch was supposed to address the issue, but the bug still persists it seems. #169 
@Masuzu

**Comment by CorrinKrow** [comment]
@Masuzu

**Comment by CorrinKrow** [comment]
![image](https://user-images.githubusercontent.com/36133340/40356669-aca2d6cc-5db1-11e8-9a6d-6091635bd2db.png)
Another instance of the bug occurring

**Comment by Masuzu** [comment]
Hello,
Ouch, my bad, I doubled check and indeed you are right.

**Comment by Masuzu** [comment]
v1.9.6 is

**Comment by CorrinKrow** [comment]
The bot seems to work fine now, thanks for the help
