### ISSUE TITLE
Sarasa crash when ep runs out

### ISSUE THREAD

**Issue by Sundaerae** [Masuzu/SarasaBot#176]
now, when ep 0, instead of refilling, sarasa crash instead.

version: sarasa 1.9.6

**Comment by ericli51** [comment]
I'm getting the same issue, occasionally when you try to join a raid wtih 0 EP Sarasa bot stops working.

**Comment by Masuzu** [comment]
The application will indeed stop by itself of EP refilling failed (due to a bad connection for instance). I will consider adding retries in case the refilling fails in the next version.
