### ISSUE TITLE
BUG:  BOT ALARM FOR ONLY 1 SECOND

### ISSUE THREAD

**Issue by nobody0014** [Masuzu/SarasaBot#177]
As the title said, the bot sounded for only a sec and stopped sounding, please fix this asap, this is actually criticle

**Comment by Zir1984** [comment]
I have the same happen every time, zoey works fine, but sarasa just procs the alarm laugh and before the jikan da closes itself. Had it happen 4 times in a row already

**Comment by Ohwhat00** [comment]
Bump for this, experiencing the same issue.  Can't leave the bot unattended due to this.

**Comment by CorrinKrow** [comment]
have the same issue as well

**Comment by Masuzu** [comment]
I could not reproduce the issue on my side after a catpcha screen was displayed during the party selection confirmation.
The default ini file has `NumNotifications` set to 9999.

**Comment by Masuzu** [comment]
Actually I spotted a potential cause leading to this observation.
It is not fixed in v1.9.9.
