### ISSUE TITLE
looping when reroll summons

### ISSUE THREAD

**Issue by sharpnelOwO** [Masuzu/SarasaBot#179]
When sarasa bot refreshed summons using trial battle.
sarasa bot says "Failed to retreat" .
idk how i fix this issue
https://www.youtube.com/watch?v=KfOEbCZsPHo&feature=youtu.be

**Comment by Masuzu** [comment]
Hello,
I spotted the issue! Thank you for reporting this.

**Comment by Masuzu** [comment]
This is now addressed in v1.9.8.
