### ISSUE TITLE
Scripting issue when using green potion and the raid ends

### ISSUE THREAD

**Issue by nobody0014** [Masuzu/SarasaBot#18]
So what happen is when the bot is trying to use green green potions and the raid ends, the bot just stuck there.
However, it does detect that the raid has ended but it still attempt to use green potion and would not do anything else (refresh included, if it has refreshed this wouldnt be a problem).
I work around this problem by having terminate the raid before the raid ends (since im botting hl raids and other summon raids that wont die instantly like magna).

**Comment by Masuzu** [comment]
Hi,

Thank you for reporting this.
