### ISSUE TITLE
Sarasa Error when party wipe

### ISSUE THREAD

**Issue by meteoshower** [Masuzu/SarasaBot#180]
Hello i have some problem when party wipe with sarasabot 1.9.6 
Sarasa got error 
![error](https://user-images.githubusercontent.com/28686592/40886644-20c4a68a-6766-11e8-80ed-9063b4c69ba9.jpg)
and this is my luascript 
` 

if turn >= 1 then
character_1:UseSkill(1)
character_1:UseSkill(2)
character_1:UseSkill(3)
end
if turn == 1 then
character_1:UseSkill(4)
end
any one can help me to solve this problem .thanks

**Comment by Masuzu** [comment]
To avoid this kind of error, you can do it like this:
```
if turn >= 1 and character_1 ~= nil then
  character_1:UseSkill(1)
  character_1:UseSkill(2)
  character_1:UseSkill(3)
end
if turn == 1 and character_1 ~= nil then
  character_1:UseSkill(4)
end
```
