### ISSUE TITLE
Sarasa Bot error when start-up

### ISSUE THREAD

**Issue by motty1050** [Masuzu/SarasaBot#182]
I updated sarasa-bot-v1.9.8.
'Sarasa Bot Unregistered user'
Licence Standard
Expiration date 6/8/2018 8:17:09 AM
Licence status Active
I tried to update my serial number,but I failed it.
'You updated your serial number less than 4 days ago.'
I want to use sarasa bot.
What should I do?

**Comment by Masuzu** [comment]
Hello,
This is intended to limit uses infringing by the terms and conditions of GBTools.
The 4 day limit may be lifted sometimes but only in exceptional cases.
