### ISSUE TITLE
 Do not get raid list

### ISSUE THREAD

**Issue by ypk1246** [Masuzu/SarasaBot#183]
i introduced SarasaBOT according to the guide, 
but reloading is repeated forever without updating the raid list.
How do I get a list?

※Twitter tokens have been set up

**Comment by Masuzu** [comment]
Hello,
Twitter may be blocked in some countries such as China, and you will have to use a VPN in such cases.
Twitter itself does not guarantee a 100% uptime in its SLAs. Restarting Sarasa works fine most of the time.
