### ISSUE TITLE
When it returns to the multi battle screen after being annihilated, the screen becomes black

### ISSUE THREAD

**Issue by kusyarudaora123** [Masuzu/SarasaBot#185]
Hello.
When it returns to the multi battle screen after being annihilated, the screen becomes black.
After the screen darkens, I will continue looking for a multi battle to put in again.
In other words, I will continue looking for a room where the summon stone selection screen will be in darkness.
Then, when you find the room specified in the condition, the mouse can not click after selecting the summon stone, so reload the page.
At that time the screen will be displayed properly.
Since the network tab of the developer tool is normal, I think that it makes a movement to select a summon stone even if the screen is dark.
There is not much hindrance for normal use, but I am a little troubled when I feel unlucky and encounter button authentication.

Since I may be the only one, if you can reproduce the same situation, please correct one.

Chrome version 63.0.3239.84

**Comment by Masuzu** [comment]
Hello,
Having a black screen can sometimes happen when you reload the page when the battle ends but the next time a page is refreshed _successfully_ (for instance when summons are loaded when you attempt to join a new raid), the black screen will disappear and the next time the ongoing raid screen is displayed, the rewards of the previously completed raid will be picked up.
The authentication button can appear sometimes when you used another device to log in, as a security measure.
It should not be a major issue in any case.
