### ISSUE TITLE
summon select with viramate

### ISSUE THREAD

**Issue by oruha** [Masuzu/SarasaBot#186]
I do not speak English well. I'm sorry.
You may move to the profile screen by clicking the user name in the compact summary list of viramate.
Please do not overlap the user name with the judgment of the place to click.

**Comment by Masuzu** [comment]
Hello,
Do not use Viramate's compact summon list and you will be fine!
![image](https://user-images.githubusercontent.com/5464705/42467221-968864a8-83b1-11e8-8d09-0b7aadad43fd.png)
