### ISSUE TITLE
Stay on the result page too short to claim rewards

### ISSUE THREAD

**Issue by sarasabothp** [Masuzu/SarasaBot#188]
after clicking on the pending raids, it instantly go back to quest page (before the page finish loading) and can't successfully claim the loots, thus started looping.

**Comment by Masuzu** [comment]
Hello,
If your ping does not allow it as described here, you may want to increase the values of the parameters MinWaitTimeInMsAfterRefresh and OngoingRaidsCheckFrequencyInSeconds under the general parameters section.
