### ISSUE TITLE
Party selection

### ISSUE THREAD

**Issue by Nassy1121** [Masuzu/SarasaBot#19]
@Masuzu 
I hope you to add "Party selection" feature.
At least one party. ( e.g. Dark wrestler)
Currently mostly select remembered party.

**Comment by nobody0014** [comment]
GBF already implement this feature where they remember which team u went into that raid with the last time

**Comment by Masuzu** [comment]
Hi,

What @nobody0014 said already indeed.
I will add a note later on in the documentation.
