### ISSUE TITLE
Can we force the bot to do "check if any completed raids" before trying to join a new one?

### ISSUE THREAD

**Issue by xerance** [Masuzu/SarasaBot#194]
Hello, seems like that the bot gets fail to join raids when there is one or more completed raids waiting in pending. I'm suspecting it to be due to the one raid limit during gw.

Is it possible to make the bot clear completed raids asap it has one or more raids completed?

I know gw is almost over, but might be useful for next run.

**Comment by Masuzu** [comment]
This feature is now available with v1.11.0
https://gbtools.azurewebsites.net/SarasaBot/en/Home/PatchNotes#1-11-0
