### ISSUE TITLE
Sarasa extensions kept getting removed every restart of Chrome

### ISSUE THREAD

**Issue by SnakeLegend** [Masuzu/SarasaBot#20]
The Sarasa Bot kept being removed every restart of Chrome itself, and have to keep reinstalling the extension manually, is that normal?

**Comment by XenoeJin** [comment]
I occasionally encounter the same issue as well

**Comment by SnakeLegend** [comment]
Got this after trying to get the extension in a dozen of times everytime it was removed.
https://i.gyazo.com/bd73ecf86db52cef10d7249d6e66a7a7.png

**Comment by SnakeLegend** [comment]
Sequence for the bot has made it to 3/3 but mouse wasn't moving observed too.

**Comment by Masuzu** [comment]
Hi,

I won't do anything about it (I also run into this "problem") but you can easily live with this minor issue.

@SnakeLegend The navigation was updated too so there is no issue on this side.
As long as there is no raid captured matching the raid list you want to join nothing will happen too.
