### ISSUE TITLE
August　17 at JP time stop Twitter real search

### ISSUE THREAD

**Issue by matp07289** [Masuzu/SarasaBot#200]
I think stop "sarasabot", Masuzu dev another join multi quest app?

**Comment by Masuzu** [comment]
Hello,
According to some people at Twitter, only certain Twitter products will be retired. Sarasa Bot should not be affected. If it is the case, then it is fine as well, I will release a different mode to track raids.

**Comment by matp07289** [comment]
https://blog.twitter.com/developer/en_us/topics/tools/2018/enabling-all-developers-to-build-on-the-account-activity-api.html

**Comment by matp07289** [comment]
https://www.theverge.com/2018/5/16/17362138/twitter-api-third-party-apps-changes-explained

**Comment by Masuzu** [comment]
Closing as it is now null and void.
