### ISSUE TITLE
How to use different scripts depending on the raid

### ISSUE THREAD

**Issue by xerance** [Masuzu/SarasaBot#205]
tittle, would be useful for multi tweet searching different raids.

**Comment by Masuzu** [comment]
Hello,
You can load other scripts using:
```
local shiva = require("shiva.lua")
shiva.DoActions(turn, battle)
```
where DoActions is a method defined in the script `shiva.lua`.

You can then combine it using the enemy name, for instance:
```
if enemy_1.name == "XXX" then
  local shiva = require("XXX.lua")
  XXX.DoActions(turn, battle)
else if enemy_1.name == "YYY" then
  local YYY = require("YYY .lua")
  YYY .DoActions(turn, battle)
  end
end
```

**Comment by NullTamer** [comment]
I attempted to use the above script but seem to be getting a syntax error on line 6.  Any help?
```

if enemy_1.name == "Slepnir" then
  local Slepnir = require("Renown.lua")
  Slepnir.DoActions(turn, battle)
else if enemy_1.name == "Ultimate Bahamut" then
  local Ultimate Bahamut = require("Basic Conjunction.lua")
  Ultimate Bahamut.DoActions(turn, battle)
  end
end
```

**Comment by Masuzu** [comment]
Yes that's exactly as you said.
Sure, will do.

**Comment by Masuzu** [comment]
Added dedicated section in https://github.com/Masuzu/SarasaBot/wiki/Lua-scripts#loading-different-scripts-depending-on-the-current-raid
