### ISSUE TITLE
Is there a way to make the bot attack and then TerminateBattle?

### ISSUE THREAD

**Issue by xerance** [Masuzu/SarasaBot#207]
Something like reverse SkipAttack and then TerminateBattle() right after?

Currently, using the:
```
if turn == x then
  TerminateBattle()
end
```
the bot reloads to the next turn and then terminates the battle, would save some time if it skipped the load in new turn phase. Is there a better way to do this?

**Comment by Masuzu** [comment]
Hello,
It is not possible to do so before taking a second turn for now.

**Comment by Masuzu** [comment]
This feature is now available with v1.11.0
https://gbtools.azurewebsites.net/SarasaBot/en/Home/PatchNotes#1-11-0
