### ISSUE TITLE
Raid Specific Support Summons?

### ISSUE THREAD

**Issue by NullTamer** [Masuzu/SarasaBot#208]
Is it possible to tie in a specific support summon to a  certain raid instead of the blanket summon?

also having trouble with this script using the sample script from the other thread. 
```
if enemy_1.name == "Qilin" then
  local qilin = require("Qilin.lua")
  qilin.DoActions(turn, battle)
else if enemy_1.name == "Ultimate Bahamut" then
  local ultimate_bahamut = require("Basic Conjunction 2.lua")
  ultimate_bahamut.DoActions(turn, battle)
  end
end

```
No errors occur but it seems to just ignore the script and attack refresh when inputting the script block.
Syntax error when using the script call up form.

**Comment by Masuzu** [comment]
Hello,
It is not yet possible to conditionally choose a summon depending on the ongoing raid.
I added a better explanation as to how to load other scripts, which you will find here: https://github.com/Masuzu/SarasaBot/wiki/Lua-scripts
