### ISSUE TITLE
Issues selecting a summon when failing to join a new raid

### ISSUE THREAD

**Issue by ngocin** [Masuzu/SarasaBot#211]
Hi @Masuzu  , though i used Zooey Bot over a year but i'm totally new with Sarasa Bot
After setting up everything , i run Sarasa Bot , open Dock, run extension, move to Quest as it said but it didn't work, didn't join anything, just stay at the Quest 
My Chromium is version 66.0.3359.181 so i think it's not a problem
![1](https://user-images.githubusercontent.com/30687323/44441274-00472300-a5f6-11e8-9eea-22f152ae2bcd.PNG)

**Comment by ngocin** [comment]
Somehow the problem was solved but I got another problem . That is when bot join a full raid, we will back to homescreen and bot start clicking random place instead of trying to join another raid

**Comment by ngocin** [comment]
![2](https://user-images.githubusercontent.com/30687323/44454595-1967c800-a626-11e8-8982-5e81ce73f111.PNG)

i don't think it will be back to trying to join

**Comment by Masuzu** [comment]
A mitigation was added in v1.11.1.
