### ISSUE TITLE
License stating it's expired in app

### ISSUE THREAD

**Issue by finaljusticemh** [Masuzu/SarasaBot#212]
For whatever reason after an update and a renewal of my license I am getting the "Renew a License" error

![image](https://user-images.githubusercontent.com/39445036/44613721-0ac80f00-a7e6-11e8-9b35-beb991b7fed1.png)

**Comment by finaljusticemh** [comment]
>.> made the purchase on the wrong account, realized it when looking at serial numbers?  Any chance for a refund? or better yet an extension to my current week?

**Comment by Masuzu** [comment]
Hello,
Sure, I can do that. Please send to support@azuriteworlds.com the serial number where you made the purchase(s) by mistake and I will refund it.

**Comment by Masuzu** [comment]
The issue was addressed privately.
