### ISSUE TITLE
Sarasabot Crashing In Avatar

### ISSUE THREAD

**Issue by moonlee7777** [Masuzu/SarasaBot#213]
I don't know what causes this, but randomly, towards the end of an avatar raid, sarasabot flat out crashes.

In addition, when sarasabot tries to use a skill but the foe has been defeated popup appears, the bot enters an infinite loop.

**Comment by Masuzu** [comment]
Hello,
Ah, the infinite loop happens without Viramate ability shortcuts. I will address this issue.
Regarding the crash, I am not sure whether it could be linked to this but it is possible when a skill cast is attempted while the raid is cleared *without* Viramate shortcuts enabled. I will take a closer look into this matter to address it this week.

**Comment by moonlee7777** [comment]
I have viramate ability shortcuts enabled.

**Comment by Masuzu** [comment]
In this case the bot is guaranteed to stop any attempts to recast a skill after `MaxNumActionRetries` (configuration parameter under the General section.
