### ISSUE TITLE
Sarasa bot trapped when battle has ended while casting skill

### ISSUE THREAD

**Issue by zappky** [Masuzu/SarasaBot#218]
In a quick paced raid such as rotb agni raid often the raid ended while the bot is still casting skill. 
This resulted in a the battle log having "The battle has ended" ,while the bot is still trying to click something. Resulting in sarasa bot unable to proceed to end the raid and proceed with the next raid.

This issue actually has been present since a long time ago,but i didnt post it here as a issue.

Please let the bot to either click the battle log, or refresh the page.

Info: Using latest version 3, not using viramate.

**Comment by Masuzu** [comment]
Hello,
This is one of the reasons why Viramate and shortcuts are highly recommended.
Normally, the skill cast attempt will be tried up to `MaxNumActionRetries` times, so that Sarasa is not permanently stuck. Wouldn't it be the case already?

**Comment by zappky** [comment]
I dont think MaxNumActionRetries variable is related to this problem because I always set it to 0. It feel it is a waste of time in pub raid unless is a crucial skill like conjunction.It would be great if we are able to specify only a certain skill to retry. In zooey bot i set it to 1, it is fine because it is solo quest ,which accuracy is more important than speed.

Coming back to the main issue , i noticed the bot seems to be trying to click "Back" button while the "The battle has ended" battle log is on . I assume the bot is trying to go to the next char for skill casting because in the battle script it is suppose to do that.
I am not sure if this is same problem or separated issue. When there is live feed on the bottom,such as the boss is in overdrive msg, the bot sometimes cannot press the char making it deem as " No response from the skill".
I have not try when the game setting "Live Battle Feed" is off , whether it will still happen or not.

Will installing Viramate circumvent the main issue?

**Comment by Masuzu** [comment]
Using Viramate and keyboard shortcuts circumvents a lot of the aforementioned issues especially when the screen has an overlay (after a boss enters break or overdrive state for instance) and no skills can be used.

**Comment by Masuzu** [comment]
https://gbtools.azurewebsites.net/SarasaBot/en/Home/PatchNotes#2-7-0
