### ISSUE TITLE
Can't update serial number

### ISSUE THREAD

**Issue by soullofts** [Masuzu/SarasaBot#22]
Hello Masuzu,
I have 2 account. my first account was used for pokerbot and zooeybot on my computer and my second account was used for sarasabot on notebook, today i want to switch sarasabot to use on my computer then i try to update serial number but the message "Name (my generated serial number) is already taken" appeared

**Comment by Masuzu** [comment]
Hi,
In this case you should log in your second account and put in a temporary "fake" serial number and then input the correct one on your main account with the active licence.
