### ISSUE TITLE
Invalid twitter creds.

### ISSUE THREAD

**Issue by kisame21** [Masuzu/SarasaBot#220]
Hi i'd like to ask regarding twitter creds. mine got approved and i tried running the bot again but it keeps showing invalid twitter creds. i have double checked it carefully. any help on what to do?

**Comment by Masuzu** [comment]
Hello,
Did you check that they were indeed correct?
If so, try to change the encoding of your configuration file (UTF8 or UTF8-BOM) depending on your Windows locale.
