### ISSUE TITLE
Bot crashes at summon select

### ISSUE THREAD

**Issue by sakroit** [Masuzu/SarasaBot#229]
When starting the bot it doesnt detect the chrome dev tools, I have them on the right side, but dont see the option in Sarasa V2.1.1

But when I start sarasa and go to quest page it gets to Summons and gives the error "Please proceed with the verification check" but no captcha is there

**Comment by NxKai** [comment]
+1 to this issue. While I attribute this error to a bad internet connection, I believe the bot should be able to compensate for slow internet.

**Comment by NoahAU** [comment]
+1, having the same problem when attempting to join raids on Sarasa V2.1.3. The bot will lockout on the summon screen waiting for a captcha to be answered when no captcha is on the screen.
