### ISSUE TITLE
Nothing happens when I start Sarasa bot

### ISSUE THREAD

**Issue by pixiehills** [Masuzu/SarasaBot#231]
I've followed the setup guide and took the steps written, although there was one thing I couldn't find under General section of sarasabot.ini, I couldn't find the ChromeDevToolsWindowDockedOnTheRight parameter. I did have chrome dev mode open and everything, do have a twitter dev account etc. But when I pressed Start on chrome extension sarasa after opening sarasa bot.exe , nothing happens.  Can someone suggest a solution to this? Thanks!

**Comment by Masuzu** [comment]
Hello,

Following issue #232 
I have released a new version with an updated extension. It would be better if you sent me the email you used to register a GBTools to support@azuriteworlds.com so I can refund you.
