### ISSUE TITLE
chrome extension sarasa bot errors

### ISSUE THREAD

**Issue by pixiehills** [Masuzu/SarasaBot#232]
Whenever I press start, I noticed nothing happened. But now I notice that every time I press start errors from sarasa bot extension pop up in chrome. this is one of them, please fix this? 
![error](https://user-images.githubusercontent.com/46279351/50562136-d399d980-0d54-11e9-83f9-c1051f459190.JPG)

I'm getting impatient because I paid for this service and can't use it until however long you take to respond. Thanks, much appreciated

**Comment by Masuzu** [comment]
Hello,

I have released a new version with an updated extension. It would be better if you sent me the email you used to register a GBTools to support@azuriteworlds.com so I can refund you.
