### ISSUE TITLE
License expired, stuck on "a transaction is under processing"

### ISSUE THREAD

**Issue by arjan127** [Masuzu/SarasaBot#236]
See title and images. I've opted for the auto renew option, however my license has expired, and the thing appears to be stuck (it's been 3 days). And that while the money does seem to have been paid on Paypal: 

![image](https://user-images.githubusercontent.com/9739865/51145400-0adbb080-1854-11e9-8e78-78abe775e329.png)

![image](https://user-images.githubusercontent.com/9739865/51145511-52fad300-1854-11e9-9755-fc52fa43f8e5.png)

If my paypal transaction ID or anything is required to confirm, I'd be happy to provide that through means of private messaging.

**Comment by falassiry** [comment]
Seconded for same exact issue,

**Comment by falassiry** [comment]
I was able to get it to work after canceling renewal via Paypal and manually renewing but that one payment that went through was lost.

**Comment by arjan127** [comment]
Ahh I'll give that a go then, thanks. But still, this is an issue I would see resolved sooner rather than later. We're paying customers and support is taking rather long to get back to us. I understand it's (probably) a one person business but it wouldn't hurt to at least say _something_.

**Comment by Masuzu** [comment]
Updates were released to recover lost transactions in the future, but since the changes were not effective yet in your case, I will have to check manually.
