### ISSUE TITLE
Lua script error since latest update

### ISSUE THREAD

**Issue by arjan127** [Masuzu/SarasaBot#239]
Hello,

ever since the update I get lua script errors, without fail, after using two character skills. It says:

"Failed to parse lua script C;\path\to\script.lua: runtime error device or resource busy: device or resource busy". First I thought perhaps I cocked up my Lua script, so I made a very simplified one. Still getting the issue, sadly.

The Lua script this happens on:

```
EnableChargeAttack()

if character_1.name == "mainCharacter" and enemy_1.charge_diamonds >= 1 then
    character_1:UseSkill(1)
end
if character_2.name == "Vaseraga" then
    character_2:UseSkill(3)
    character_2:UseSkill(2)
    character_2:UseSkill(1)
end
if character_1.name == "mainCharacter" then
    character_1:UseSkill(3)
    character_1:UseSkill(2)
    character_1:UseSkill(1)
end
character_3:UseSkill(3)
character_3:UseSkill(2)
character_3:UseSkill(1)

character_4:UseSkill(3)
character_4:UseSkill(2)
character_4:UseSkill(1)
```

[obviously replaced my character's name for mainCharacter]

**Comment by csyeul** [comment]
I'm not an expert but I think this error occurs when you have too much things going on your computer. Try to close few programs and retry?

**Comment by Masuzu** [comment]
Hello,
This is a first. I will try and look into it. Does this happen with the previous version as well? 
This would also affect Zooeu bit but I got no such reports.

**Comment by arjan127** [comment]
I can't say I've tried with a previous version yet so I'd have to look into how to get one. At a glance I can only see the latest version available to download so will require some digging, I guess.

There was one occasion with a previous update where I opted not to update the bot as I had to leave for an hour or so, so I intended to just run it while I wasn't at the PC. However, when doing so it told me that my license had expired so I just assumed that old versions cannot correctly retrieve your license status and you're always required to run the newest version.

**Comment by appleloli** [comment]
Hello also getting this error, only happening with 2.2 no issues with 2.1.3

![image](https://user-images.githubusercontent.com/35543465/51655485-0b610d80-1ff1-11e9-8d50-42b7909a67bd.png)

**Comment by jucky330** [comment]
hi
I confirmed the same phenomenon,occurs when using viramate.

**Comment by Masuzu** [comment]
Hello,
This time around I can't find any explanation for the error: it would just have happened in the previous version 2.1.3 as well, which is enclosed there:
[sarasa-bot-v2.1.3.zip](https://github.com/Masuzu/SarasaBot/files/2799418/sarasa-bot-v2.1.3.zip)

In any case, a new build of the last version 2.2 was re-released.

**Comment by arjan127** [comment]
Hello,
I tried running both the newest build as well as the older version.
The new version gives the same error, whereas the old version seems no longer capable of joining a raid. It sat there for 10 minutes attempting and failing to join any raid.

**Comment by Masuzu** [comment]
Unfortunately it looks like that the probel is isolated and only you experience it. I can't reproduce it either.
However, regarding the turn count not incrementing , that is something I will look into.

**Comment by Runaris** [comment]
[https://puu.sh/CEkRh/0285164263.png](url)

here is an image of the turn counter not incrementing. Seems to be affecting skills as well as it will sometimes constantly tap skills thinking it can use them but it can't.

**Comment by Masuzu** [comment]
Thank you, from the console logs I can see why the turn stayed as 1 after the first attack but it should not have been the case for the other turns 🤔 v2.3.1 addressed a certain bug which prevented turn increments. However, in your case, it seems that you have some other extensions running which mess up with your turn count.
On a side note, you should maybe consider using `ReloadPageOnLastBattle=true` if the raids you join are  cleared too fast.

**Comment by Runaris** [comment]
sync turn option is off, synchronize difference between raid windows is also off.

https://puu.sh/CF1qP/3b5d920774.png still happening.

I have removed every extension from chrome, there should be nothing interfering with it anymore.

There is only one chrome window open. I usually restart the laptop running this before I do anything on it.

**Comment by Masuzu** [comment]
Ah, that's unfortunate that the bug still persists with v2.3.1.
That helps narrowing the root cause though. Thank you for the feedback.

**Comment by Runaris** [comment]
back to the original thread though, I am still getting "Lua script error : device or resource busy : resource busy" error as stated above

this time with an ULTRA SIMPLE lua script, something which just clicks skills and then presses attack for 5 turns before terminating the battle. I can't get much done with the lua error that is now rife. I can usually get about 7 or 8 raids joined before the error pops up, if that helps. But its almost completely random.

**Comment by arjan127** [comment]
As far as I can, the error only happens when you tell it to use skills. Perhaps it's an issue that happens alongside Viramate (IE: using the shortcuts). I haven't been able to test it without as my license expired unfortunately.

**Comment by Miyoumu** [comment]
I can confirm that the issue is still persisting and only happens when Viramate use is true.

**Comment by Masuzu** [comment]
Stability improvements regarding this issue were added in the last version 2.3.2.

**Comment by Runaris** [comment]
2.3.2 freezes or stalls after "good to go" appears on the command window

doesn't seem to progress past this.

**Comment by Masuzu** [comment]
I apologize for the delay in the response, v2.3.3 should have addressed these issues.

**Comment by Masuzu** [comment]
However, I acknowledge that this time around this must be one of the most inextricable bug reported, and that the provided solution is more or less guesswork and addresses additional edge cases. For instance, I still do not see how the UseViramate parameter would change anything regarding whether that exception is raised or not.

**Comment by Runaris** [comment]
maybe its time to look at how your program is interfacing with viramate. If just one option causes the error which in this case is "UseViramate" it might be the way your program interfaces with viramate, or it might be something in viramate that could be messing with it. Viramate's update which changed a bunch of things did have some effect (split hotkeys into various sections) on this program so maybe its worth an investigation by tearing into viramates files.
