### ISSUE TITLE
Invalid Twitter Credentials

### ISSUE THREAD

**Issue by Bakamoto** [Masuzu/SarasaBot#24]
On startup the application always closes after it says invalid twitter credentials. Went through the .ini and made sure everything was copied from the twitter app, and it still continues. Is it on my end? 
edit: also saved encoding as UTF8 using notepad ++

**Comment by Bakamoto** [comment]
Solved, when you first edit the .ini, use notepad ++ from the getgo. Reinstalled it and opened it first instead of the default notepad application and setting it as UTF8.

**Comment by Masuzu** [comment]
All good then!
