### ISSUE TITLE
Sarasabot (fail to join raids) 

### ISSUE THREAD

**Issue by Runaris** [Masuzu/SarasaBot#240]
[https://puu.sh/CDOim/8fa28d0fa7.png](url)

@Masuzu 

Was working fine to a point a day before, where a bug I noticed was Sarasabot not counting up the turn counter. So all my luascripts were broken. Meaning Sarasabot would constantly think its "turn 1"

Well now it just doesn't join raids at all, no matter what I pick or do it just outright fails without explaination. Every single raid goes by is "fail to join raid" Either something happened on the GBF backend which has nuked the extension's ability to work or this release is bugged to all hell.

I spent all morning trying to debug this and figure out if its the computer or my config file or something else amiss and I just can't find why its doing this.

I noticed previously there was a GBF maintenance earlier. It might have done a few things.  Might have to look into what changed because the program is non-functional at this point and my license is still ticking.

**Comment by ErogeSeiyuu** [comment]
Can confirm, Failed to Join Raids everywhere post-maintenance.

**Comment by Masuzu** [comment]
An updated version was released. Let me know in another issue thread if you find out other bugs. Thank you
