### ISSUE TITLE
Auto-Renewal

### ISSUE THREAD

**Issue by lamewood** [Masuzu/SarasaBot#241]
Hello Masuzu!
I've clicked on the auto-renewal of Sarasa last week at this time and it charged me 4,79€ which was fine for the initial pay, but it said that the 2nd payment would be for 3,99€
My issue is, that the payment was still 4,79€
Can you help me out with this situation?
my email is lamew00d@hotmail.de
Greetings!

**Comment by Masuzu** [comment]
Hello,
Prices now include a 20% VAT part, which results in the 4,79 price tag, which should be detailed in the Paypal transaction breakdown as well.
