### ISSUE TITLE
Getting less than half subscription time

### ISSUE THREAD

**Issue by chaitat2009** [Masuzu/SarasaBot#242]
I just purchase sarasa bot today. but I only got 13 Days only (shouldn't it be like 30 days?).
What should I do?

![why](https://user-images.githubusercontent.com/5485052/52179460-7985ab80-280d-11e9-844e-556b69333c11.png)

**Comment by ErogeSeiyuu** [comment]
![image](https://user-images.githubusercontent.com/28994631/52182022-bc706080-27c6-11e9-8036-6e3b56228748.png)

**Comment by Masuzu** [comment]
Hello,
The licence renewal for Sarasa bot is weekly while Zooey bot is monthly.
