### ISSUE TITLE
2.3.2 broke Sarasa

### ISSUE THREAD

**Issue by ErogeSeiyuu** [Masuzu/SarasaBot#244]
1. Open gbf on chrome, F12
2. Start sarasabot
3. Press Start on chrome addon (only works 33% of the time, the other 66% clicking Start does nothing on 2.3.2)
4. Set up ok, step 3/3 on command console. It will stuck here and does not prompt "Go to to quest page" 

rolled back to 2.3.1 and it's normal again.

**Comment by jstwayy** [comment]
having this issue as well

**Comment by Jinko78** [comment]
Same issue

**Comment by komagi** [comment]
same here

**Comment by Masuzu** [comment]
Looking into it.

**Comment by Masuzu** [comment]
I apologize for the delay in the response, v2.3.3 should have addressed these issues.
