### ISSUE TITLE
Stuck on boss killed by other team

### ISSUE THREAD

**Issue by Sundaerae** [Masuzu/SarasaBot#245]
The bot always stuck when the raid is killed by other team. 
It happened right when the bot supposed to click back. It won't dismiss the "Boss already killed" pop up nor will it reload. It will always hover and try to click the <back> button, but it can't since there's a pop up hindering it.

**Comment by Jinko78** [comment]
Agreed this is a problem, need something to dismiss the pop up when a boss is killed o refresh the page.

**Comment by Masuzu** [comment]
I will fix this this week.
In the meantime the UseViramate option does not have this issue.

**Comment by Sundaerae** [comment]
I don't know whether this is the same issue as the other topic: if I set the viramate to highlight the skill icon (instead of selecting the character), the bot often crashes. So even though I use Viramate, I uncheck the 'select skill icon' option. This leads me to the back button problem, same as if I don't use Viramate.

**Comment by Sundaerae** [comment]
So if I enable the highlight quick panel
![viramate option](https://user-images.githubusercontent.com/31296536/52873453-9dd47700-3181-11e9-95ed-f8366bdef49b.png)
It would end up stopping
![sarasa error](https://user-images.githubusercontent.com/31296536/52873466-a3ca5800-3181-11e9-885e-52b55ca1c2b2.png)

But if I disable it (just like the first image), it won't but will have the 'back button' problem.
And it still happens on 2.3.7

**Comment by Einhalkzt** [comment]
im having the same issue and im also using viramate, @Masuzu did you turn on the auto end fight thing?

**Comment by Masuzu** [comment]
No, I never had this viramate feature enabled.
