### ISSUE TITLE
2.3.4 Sarasa keep stop working 

### ISSUE THREAD

**Issue by komagi** [Masuzu/SarasaBot#246]
Sarasa keep stop working . after click Attack button . 
no reload or anything no error message then Sarasa Close itself

**Comment by Jinko78** [comment]
Yup, getting this as well.

**Comment by Masuzu** [comment]
I will revert some changes added in v2.3.4 then.

**Comment by ngocin** [comment]
same problem, please fix it fast for guild war

**Comment by Masuzu** [comment]
The version 2.3.5 reverting changes in v2.3.4 has just been released.

**Comment by ngocin** [comment]
@Masuzu 
![image](https://user-images.githubusercontent.com/30687323/52815091-4f1ad480-30d0-11e9-984c-d4a5bb093a9b.png) the new version keep stop working due to this

**Comment by Masuzu** [comment]
Thank you for the feedback. Update: I managed to reproduce some of the issues and pushed another update (2.3.7)

**Comment by ngocin** [comment]
@Masuzu sometimes , instead of joining a raid ,bot take me to MyPage , with the url is the url of raid then stuck at that without shutdown itself

**Comment by Masuzu** [comment]
@ngocin This is actually a non-issue and can happen when the raid completed by the time you tried to load the summon selection page.

**Comment by Masuzu** [comment]
@ngocin Ah sorry, I see what you mean. A bugfix for this was added in the v2.3.9
