### ISSUE TITLE
Can't use summon in raid

### ISSUE THREAD

**Issue by GivemeDokkan** [Masuzu/SarasaBot#248]
Hi,
Could you please check this out, the bot keep crashing when try to use summon in battle.

I'm a totally newbie to this programming stuffs, so maybe I did something wrong.

![53243163-99f0a980-36d9-11e9-9193-48386c2dc6e8](https://user-images.githubusercontent.com/47890542/53255194-ba2f6100-36f7-11e9-8a74-82fba10b14ce.JPG)
![53243164-9a894000-36d9-11e9-8144-b725e498e4dc](https://user-images.githubusercontent.com/47890542/53255197-ba2f6100-36f7-11e9-92ec-b411ad9e9103.JPG)

**Comment by Sundaerae** [comment]
try using Summon() instead of summon()
