### ISSUE TITLE
zero raid capture

### ISSUE THREAD

**Issue by skyfishjy** [Masuzu/SarasaBot#25]
I followed the instruction step by step(twitter, UTF8, and other stuff, ) but the bot can't join any raid(there is a raid in the list just like the picture above show and there are many raid in the tweetdeck meanwhile) 

I only changed the twitter key/secret section in .ini file

do you have any suggestion? . thanks.
![default](https://user-images.githubusercontent.com/996019/34088438-c20a5fe2-e3ec-11e7-9f08-e6470c5d6e6c.JPG)

**Comment by Masuzu** [comment]
Hi,

With the latest version, please make sure to have `DisplayRaids` set to true. If you do not have any raids showing in the console then it means that your Twitter app permissions are probably badly configured or you may have reached Twitter bandwith limits.

My Twitter app permissions are configured as follows:
![image](https://user-images.githubusercontent.com/5464705/34260545-9d63efba-e666-11e7-8612-a2f66330cffd.png)

**Comment by nobody0014** [comment]
I have the same problem too, every 30+ min to 50 min it just stopped working (i have the same setting app permissions- read & write).

**Comment by Masuzu** [comment]
If you happen to share your Twitter app with someone else this is very likely to appear due to "normal apps" restrictions. I'd attribute this issue to external factors on which I do not have any leverate.

**Comment by agesa** [comment]
I began getting this problem after running it successfully last night for a few hours, and I have no idea why.  Nothing was changed between it working and it not working.

**Comment by nobody0014** [comment]
I think it's more of twitter API crapping out and more like internet being shit too (i have them from time to time). I will make another issue for a proposal  to solve this problem
