### ISSUE TITLE
Runtime error device or resource busy: device or resource busy.

### ISSUE THREAD

**Issue by WVVWVWVVW** [Masuzu/SarasaBot#250]
My script runs fine except it occasionally will get stuck on the raid concluded message. I followed the advice of someone and installed viramate for the automatically end raid battle setting, but now my script seems to crash the bot. 
Edit just to clarify, I have enabled the shortcut options in Viramate, and enabled Viramate in the .ini file of Sarasa, and I've made sure that the .lua file is encoded in UTF-8

**Comment by Jinko78** [comment]
Getting this also, only since the latest Sarasa update.

**Comment by Anelfe** [comment]
Same as above issue
