### ISSUE TITLE
When does the bot check current hp of enemy? (enemy_1.hp)

### ISSUE THREAD

**Issue by xerance** [Masuzu/SarasaBot#252]
Cause I have a bunch of "if enemy_1.hp > x then" in the skill condition to force a refresh between skills to avoid animation locks, but it seems like this isn't working properly cause it still tries to summon/use skills under the hp treshhold.

**Comment by Jinko78** [comment]
You would be better off using percentage IMO
enemy_1.hp_percentage

**Comment by xerance** [comment]
it yield the same result, so not sure why it would matter?
the issue isn't the condition, its set up properly. it just simply doesn't check against the current hp right when the condition is given as far as I can tell.

**Comment by Masuzu** [comment]
Currently the HP checks are only performed at the beginning of the turn and after each of your actions, so if other players performed other actions, the new HP won't be taken into account.
