### ISSUE TITLE
Failed to parse lua script

### ISSUE THREAD

**Issue by MegaBlues** [Masuzu/SarasaBot#253]
I've been getting that "Failed to parse lua script C;\path\to\script.lua: runtime error device or resource busy: device or resource busy". error recently. It seems to pop up randomly when attempting to use a skill on version 2.3.10.

**Comment by MegaBlues** [comment]
To update, it seems like this only pops up when attempting to use skills that target party members.

**Comment by sam-f-owens** [comment]
Do you have EnableEarlyTurnStartWithViramate=true or UseViramate=true? Both of those were causing issues for me

**Comment by MegaBlues** [comment]
I have UseViramate set to true. Hopefully disabling it fixes the issue.
