### ISSUE TITLE
Initialization 2/3 stuck

### ISSUE THREAD

**Issue by stanjun232** [Masuzu/SarasaBot#255]
Stuck on initialization 2/3 while the console keeps loading the raid list into the console. tried navigating to quest and reloaded and such.

nothing is wrong with my scaling ( because zooeybot works but this doesn't )
can someone probably help ? thanks in advance

**Comment by stanjun232** [comment]
nvm, closing and reopening it few times did the trick

**Comment by BB951** [comment]
@stn232 Sorry for commenting on closed issue, but I am facing the same issue as you with Initialization stuck at 2/3 "_Please make sure to open the Chrome DevTools by pressing F12_".

Could you elaborate a little on how you managed to fix it? I have tried closing and reopening both the browser & Sarasa, but nothing changed.

**Comment by stn232** [comment]
well @bb951 me myself too am not sure about what fixed this issue for me. i
just tried different kind of things like opening and reopening devtools,
opening sarasabot while on quest menu and click to home menu, etc etc. and
then i tried opening and reopening few times and voila, it was working again

**Comment by BB951** [comment]
Thank you! I tried a few different things too as you said, while also closing some other extensions (including Viramate), and it's working fine now. Cheers
