### ISSUE TITLE
will there be a measurement on the changes that been maken by viramate?

### ISSUE THREAD

**Issue by Keylein** [Masuzu/SarasaBot#256]
Due to the anti-cheat that perform by cygames,
Viramate's founder disable's first character's first ability shortcut.
and it have already last for almost 2 months.

And the bot will now jammed at that skill and wont move anymore so i have to disable the useViramate function.
this letting the farming of multi-person raid a lot harder due to the low efficiency and make me realise these problems:
1:Which the bot will always back and select character but not using < and > to select the correct character and will press back AGAIN even if i use 2 summons in a row.
2:the bot cant read the exact information everytime they retry, for example, after they press  a summon but the previous action need more time then the skill's min wait time. the summoning action will be add to the skill lineup and to perform after the previous skill completed. Indeed the bot will still state it as using summon fail and retry, bot will NOT perform another check but keep retry on clicking a summon which is already in CD time.

really hope there will be a measurement that helps the bot's become smarter.

**Comment by MegaBlues** [comment]
![image](https://user-images.githubusercontent.com/39666963/54078647-e9b69f80-4299-11e9-95c6-582647627fe7.png)

Disable this.
