### ISSUE TITLE
Sarasa Keep reloading 

### ISSUE THREAD

**Issue by ariaanaa** [Masuzu/SarasaBot#258]
![messageImage_1553004024500](https://user-images.githubusercontent.com/28663376/54615198-a24dc180-4a98-11e9-90f8-33a2525d6495.jpg)

can anyone help? first it run like normal then after several minutes the bot keep reloading without joining the raid it self. Is there any solution for this? thanks

**Comment by agesa** [comment]
Same problem.  Occasionally it'll work fine on its own, but the vast majority of the time it just stops receiving codes after a while.  Resubbed a day ago and I can't get it to work properly anymore.

**Comment by NaoiKR** [comment]
Can confirm this is happening to me too. After some time, sarasa stops receiving codes and just reloads.

**Comment by sujiC** [comment]
Same problem here.

**Comment by Masuzu** [comment]
The Twitter connection may be reset in certain cases which cause the supply of raids to dry out. I will keep this in mind for future releases to see if something can be done about this.
