### ISSUE TITLE
Bot just keeps searching for raids

### ISSUE THREAD

**Issue by Akkarin999** [Masuzu/SarasaBot#259]
![image](https://user-images.githubusercontent.com/48862535/54868232-4bf8bf80-4dc5-11e9-9bdb-47c2314ee0ae.png)
I basically added all the raids from the list into the source file but the bot just keeps searching with no other actions =/ anything im doing wrong? If more info regarding my settings is needed, I will be able to provide thanks!

Edit: realized need to open the chrome dev pagefor the code to run but even after setup success, there are no green raids that I can joiin, currently wish to farm the  Xeno Ifrit event, the code is just running searches non stop as per the screenshot

**Comment by BB951** [comment]
I am having a similar issue, but instead am stuck on detecting the Chrome DevTool after pressing "Start" on the Sarasa extension. I am able to calibrate in Zooeybot with no problems, but only getting this issue at Sarasa: 

![Issue](https://user-images.githubusercontent.com/40469795/54881374-11a52600-4e8a-11e9-8701-371e45830328.PNG)

**Comment by Koraxor** [comment]
Should be using
Lvl 100 Xeno Ifrit,Lv100 ゼノ・イフリート

To search for xeno ifrit.

**Comment by Akkarin999** [comment]
> Should be using
> Lvl 100 Xeno Ifrit,Lv100 ゼノ・イフリート
> 
> To search for xeno ifrit.

Thanks, the latest error I am receiving is this

![image](https://user-images.githubusercontent.com/48862535/54891240-b73ab280-4ee7-11e9-9d05-4c128587ed59.png)

**Comment by Koraxor** [comment]
Try disabling ublock/adblocker maybe?

**Comment by Akkarin999** [comment]
Yeps tried it, one of he error is gone but the program is still stuck =/  anyone facing similar issues/error messages?
![image](https://user-images.githubusercontent.com/48862535/54891829-e520f680-4ee9-11e9-97e0-8d7f24c276d5.png)

**Comment by Koraxor** [comment]
Try disabling some other extensions you have running on there one by one, quick google searches shows the unchecked runtime error is caused by extensions not interfacing correctly. Could also try re-installing the sarasabot extension. The failed to execute postmessage error is fine though, don't worry about that one.

**Comment by Akkarin999** [comment]
![image](https://user-images.githubusercontent.com/48862535/54893886-e73b8300-4ef2-11e9-9e88-e3b44c76a490.png)
if i dont run the program or anything its fine
![image](https://user-images.githubusercontent.com/48862535/54893917-1baf3f00-4ef3-11e9-94a3-1818fa58c68e.png)
but once I run it the error comes out, already turned off all extensions and reinstalled sarasabot in extensions. not sure if its because I did not select the Medium window size as stated in the instalation guide because the link included there already does not have thiis option, *insert i have no idea what Im doing meme 
https://github.com/Masuzu/SarasaBot/wiki/Setup-and-installation

**Comment by Akkarin999** [comment]
Yeps ok issue resolved, turns out yes, it was the screen size that was the issue. Once I headed to settings to turn off automatic resizing, the options for the screen size came out and after that the program worked
