### ISSUE TITLE
Lua script encoding issue

### ISSUE THREAD

**Issue by violafayde** [Masuzu/SarasaBot#26]
![image](https://user-images.githubusercontent.com/33265321/34249187-cdb20870-e673-11e7-9218-7674cf19b725.png)

Not sure what's going on, I enter a raid and the bot tries to load the lua script but it just crashes.

UPDATE: using a clean version of one_punch.lua seems to be fine, but once i add anything to that script the bot crashes when it tries to load.

**Comment by Masuzu** [comment]
Hi,
This is very likely caused by wrong encoding of your Lua script.
Make sure to save it as UTF8. I had the same happening a while ago.

**Comment by violafayde** [comment]
I saved it as UTF-8, but it still refuses to load properly.
I used notepad++ and changed the encoding to UTF-8.

**Comment by Masuzu** [comment]
Oddly enough the ini file for Sarasa bot sometimes has to be encoded with UTF8 without BOM with some Windows locales. If you can use the one_punch provided, just use the same encoding for your own scripts.

**Comment by violafayde** [comment]
one_punch works fine on its own, but as soon as i modify it (e.g. characters["Tien"].UseSkill(1))
it crashes the bot when it tries to load the script. If i revert the changes, it works again.

**Comment by Masuzu** [comment]
Ah, by the way, the correct syntax is `Characters["Tien"]:UseSkill(1)`
