### ISSUE TITLE
Sarasa having trouble refilling bp

### ISSUE THREAD

**Issue by Rkdheishins** [Masuzu/SarasaBot#263]
when you don't have enough bp sarasa will attempt to refill not in the back in but a pop up will occur and then sarasa will not click the button to refill but eventually refresh the screen then while the screen refreshes add bp in the back in, in essence increasing the time taken to join raids

**Comment by Geo8342** [comment]
Can confirm.

**Comment by Gutenhl** [comment]
for now just set additional ep refill to like 50 lol

**Comment by Rkdheishins** [comment]
that's a workaround for now yes, but there goes you bp refill from 0-10 when your not playing :(

**Comment by NaoiKR** [comment]
Actually I’m having the same problem, but my sarasa doesn’t refresh the page and just bugs with the BP refill screen.

Other problem I’m having that probably is related is that sarasa gets stucked when you join 3 raids. The bot keeps trying to join one more RAID and bugs with the “you can only join 3 raids” notification.

**Comment by Rarow** [comment]
> Actually I’m having the same problem, but my sarasa doesn’t refresh the page and just bugs with the BP refill screen.
> 
> Other problem I’m having that probably is related is that sarasa gets stucked when you join 3 raids. The bot keeps trying to join one more RAID and bugs with the “you can only join 3 raids” notification.

Yes i am having the same problem, using version 2.4.1 when my bp is empty sarasa will show the menu to use berry but it will stuck there and doesn't do anything. Screenshot: https://ibb.co/0Fj6hfG. @Masuzu please fix this too sir.

**Comment by krypticsalt** [comment]
Same issues as NaoiKR mentioned, would be nice if there was a workaround/fix before xeno ends.

**Comment by Masuzu** [comment]
Bugfixes were added in v2.4.4.
As an alternative the previous quick raid joining feature is still available through the parameter `QuickRaidJoining`, but is disabled by default.

**Comment by MegaBlues** [comment]
In v.2.4.4 and v.2.4.5., QuickRaidJoining doesn't work and refilling BP is semi-broken. If QuickRaidJoining is off, Sarasabot will never refill BP but will refresh the page after enough time has passed, sticking itself in a loop. If QuickRaidJoining is enabled, BP will be refilled if there isn't enough to join a raid. Instead, regardless of how much BP the user has, Sarasabot will never navigate to the summon select screen, instead going from the Quest menu after refilling BP to the Raids tab under the Raids menu after failing to join a raid (It doesn't navigate at all to the "Enter ID" tab).

**Comment by Masuzu** [comment]
As a workaround, the version 2.4.8 now forces BP refills and will just display a warning message instead of being stuck.
