### ISSUE TITLE
Version 2.4.2 was fine 2.4.4 broke everything

### ISSUE THREAD

**Issue by Rarow** [Masuzu/SarasaBot#264]
Using version 2.4.2 i have no more problem refilling bp. But after using 2.4.4 that problem surfaced again, sarasa did refresh but it didn't refill the bp even though i already set AdditionalNumSoulBerriesToUsePerRefill=50, 
then it will try to join a room but of course i can't join because the bp is still empty then it will refresh and try to join a room again. it just goes on like that 

Another problem is after sarasa enter the raid id it takes way too slow to click "join a room" I didn't have such problem using version 2.4.2. So I tried changing these: 

DelayInMsBetweenMouseDownAndUp
RandomDelayInMsBetweenMouseDownAndUp
MouseSpeed
MouseScrollSpeed
WaitTimeInMsBeforeClickInput

But the problem still persist. Please help thank you

**Comment by Masuzu** [comment]
Looking into it. In the meantime you can still use the quick raid joining feature by setting the parameters QuickRaidJoining to true under the general section of the configuration file.

**Comment by Masuzu** [comment]
Closing this thread.
Learnings: BP refill is broken.
It is not possible anymore to navigate directly to the summon selection page from anywhere.
