### ISSUE TITLE
2.4.7 doesn't count turns at all and fails to load scripts randomly.

### ISSUE THREAD

**Issue by devvah** [Masuzu/SarasaBot#266]
In new version regardless if you have ReloadPageOnLastBattle true or false Sarasa will always count turn 0 making scripts fail.

![obraz](https://user-images.githubusercontent.com/30633684/55290181-32143980-53d0-11e9-81b9-b0c163952015.png)

Edit: I should have noted Im not using viramate.  Im also not using QuickJoin so Sarasa doesn't refill berries at all.

For some reason sometimes doesn't seem to read scripts at all and TerminateBattleAfterAttack() won't do anything even if it's the only thing in script, bot will just attack as if script was empty.

Confirming - bot doesn't display Script loaded in log randomly which causes behaviour as if there was no script.

Edit2: This isn't random, it's from 2nd raid onward where script isn't loaded.

**Comment by Cyuss321** [comment]
The previous version seems to work fine, so obviously something in the update broke the turn counter. Hope this gets resolved soon.

**Comment by Masuzu** [comment]
A bug was identified which would cause the turn count to be 0 and was included in v2.4.8
