### ISSUE TITLE
BP Refill Still Not Working

### ISSUE THREAD

**Issue by Rarow** [Masuzu/SarasaBot#267]
Using version 2.4.8, BP refill is still not working, just the same problem like in 2.4.4. Even until now i am still using 2.4.2 because BP refill is working using that version.

**Comment by Masuzu** [comment]
Could you please show a screenshot of the console messages when this happens and indicate the current BP you have when it should refill them?

**Comment by Masuzu** [comment]
Update: I managed to get such an occurrence and am currently investigating it.

**Comment by Rarow** [comment]
Here is the screenshot sir https://ibb.co/QMTq0nw, hope it helps.

**Comment by Masuzu** [comment]
Thank you very much for the details. Good news, I identified the issue and a release is on the way within the next 30 minutes.

**Comment by Masuzu** [comment]
The update is now live: https://github.com/Masuzu/SarasaBot/releases/tag/2.4.9
Hopefully this is the last one regarding this matter.

**Comment by MegaBlues** [comment]
In 2.4.9, Sarasabot still doesn't refill BP properly. It refills once it gets to the Enter ID raid screen, but doesn't dismiss the refill popup, and the raid joining only resumes once the page refreshes due to there not being any raids to join.

**Comment by angeloid1987** [comment]
> In 2.4.9, Sarasabot still doesn't refill BP properly. It refills once it gets to the Enter ID raid screen, but doesn't dismiss the refill popup, and the raid joining only resumes once the page refreshes due to there not being any raids to join.

the same issue here

**Comment by angeloid1987** [comment]
it's refill BP, but stuck at refill BP popup

**Comment by Masuzu** [comment]
After refilling BP (this is done outside of the BP popup menu), Sarasa will try to rejoin the same raid. Since the current page is still the Enter ID raid screen, a page refresh should be triggered with the current version and things should resume as usual.

**Comment by Rarow** [comment]
> After refilling BP (this is done outside of the BP popup menu), Sarasa will try to rejoin the same raid. Since the current page is still the Enter ID raid screen, a page refresh should be triggered with the current version and things should resume as usual.

Unfortunately no, it did refill the BP but the page didn't refresh, so it is just stuck on the BP menu popup.

**Comment by Masuzu** [comment]
Going into deep waters then, a small change was added in v2.4.10 which supposedly checks whether the page should be refreshed or not. After a BP refill – when the QuickRaidJoining mode is disabled – if you have in the console the letter 'B' displayed instead of 'A' while you are still on the Enter raid ID screen, something is going wrong.

**Comment by Rarow** [comment]
> Going into deep waters then, a small change was added in v2.4.10 which supposedly checks whether the page should be refreshed or not. After a BP refill – when the QuickRaidJoining mode is disabled – if you have in the console the letter 'B' displayed instead of 'A' while you are still on the Enter raid ID screen, it means that something is going wrong.

Thank you sir masuzu, it's working perfectly now and the refresh is fast too. Hopefully there is no more problem now.

**Comment by krypticsalt** [comment]
2.4.10 also fixed any issues i had with BP, thanks.

**Comment by Masuzu** [comment]
Glad to hear!
