### ISSUE TITLE
Sarasabot not tracking any raid

### ISSUE THREAD

**Issue by ctdtnork** [Masuzu/SarasaBot#269]
I suddenly have an issue with sarasabot not tracking any raid.

it keep trying to join a raid but he is not tracking any.

![image](https://user-images.githubusercontent.com/49250980/55506126-f8a03000-5654-11e9-9ffe-60f5ed2d424e.png)

I've try to refresh my twitter keys etc but it doesn't change anything.

**Comment by Rarow** [comment]
> I suddenly have an issue with sarasabot not tracking any raid.
> 
> it keep trying to join a raid but he is not tracking any.
> 
> ![image](https://user-images.githubusercontent.com/49250980/55506126-f8a03000-5654-11e9-9ffe-60f5ed2d424e.png)
> 
> I've try to refresh my twitter keys etc but it doesn't change anything.

I have this problem too after running sarasa for about 1 hour, it just keep refreshing and not joining any raid even though there is new raid. and i set sarasa to run for 2 hours

**Comment by NaoiKR** [comment]
Bump 

This one still happens

**Comment by Masuzu** [comment]
Hi,
Related to https://github.com/Masuzu/SarasaBot/issues/278
