### ISSUE TITLE
about sarasa bpt extension

### ISSUE THREAD

**Issue by aftercrisis** [Masuzu/SarasaBot#27]
when I run sarasabot.exe it run smootly and show raid code
but when I back to gbf page click start in the sarasa bot extension not thing happen 
please help what I did wrong 

![image](https://user-images.githubusercontent.com/34739152/34251946-56652ecc-e674-11e7-8e59-fcc35ab65741.png)

**Comment by Masuzu** [comment]
Hi,

Please remove and reload the extension.
