### ISSUE TITLE
Sarasa bot crashing when  raid boss die 

### ISSUE THREAD

**Issue by nutteda** [Masuzu/SarasaBot#271]
Sarasa bot run perfectly for short time and sometime when raid boss die it crashing without any warn

my .lua

character_1:UseSkill(3)
character_1:UseSkill(1)
Summon(6)
if turn == 2 then
character_2:UseSkill(1)
character_2:UseSkill(3)

character_3:UseSkill(4)
character_3:UseSkill(1)
character_4:UseSkill(3)
character_4:UseSkill(2)
character_4:UseSkill(1)
end

my .ini
RaidsToTrack=Lv120 グリームニル,Lvl 120 Grimnir

MaxNumPlayersInRaid=10
MinimumRemainingBossHpPercentage=50
MaximumRemainingBossHpPercentage=100
RaidRequestTimeToLiveInMs=180000
MinDelayInMsBeforeTryingToRejoinRaid=20000
DisplayRaids=true

[General]
Language=en
MaxNumSoulBerries=9999
AdditionalNumSoulBerriesToUsePerRefill=0
MaxNumSoulBalms=9999
UseSoulBalmsWhenNoRemainingSoulBerries=true
UseSoulBalmsFirst=false
MaxPageLoadDelayInMsBeforeRetry=3500
MaxTriggerDelayInMsBeforeFallback=5000
MaxResponseDelayInMs=2000
MaxNumActionRetries=1
MinWaitTimeInMsAfterRefresh=2000
TimeLimitInSeconds=21000
UseViramate=false
OngoingRaidsCheckFrequencyInSeconds=10
WaitForRaidEndBeforeJoiningNewRaid=false
CountdownTimerHorizontalPosition=0
CountdownTimerVerticalPosition=0
FastRaidRewardCollection=false
MaximumDelayInMinutesBeforeAttemptingToRetreatFromARaid=10
QuickRaidJoining=false
[Inputs]
DelayInMsBetweenMouseDownAndUp=40
RandomDelayInMsBetweenMouseDownAndUp=20
MouseSpeed=700
MouseScrollSpeed=700
ExitKeyCode=112
WaitTimeInMsBeforeClickInput=50
[Summons]
PreferredSummons=shiva
DefaultSummonAttributeTab=Misc
RerollSummonWhenNoPreferredSummonWasFound=false
[Combat]
MinWaitTimeInMsAfterAttack=200
MinWaitTimeInMsAfterSummon=3000
MinWaitTimeInMsAfterAbility=1750
LuaScript=Scripts/HL2.lua
ReloadPageOnLastBattle=true
MaxInactivityPeriodBeforeLeavingTheRaidInMs=6000
EnableEarlyTurnStartWithViramate=false
MinWaitTimeBeforeActionAfterEarlyTurnStartInMs=1500
AdditionalDelayInMsAfter2ChainBurst=1500
AdditionalDelayInMsAfter3ChainBurst=5000
AdditionalDelayInMsAfter4ChainBurst=7600
AdditionalDelayInMsAfterOverchainBurst=7600

[Debug]
Clicks=false
ForceRaidRewardCollection=false
ForceRaidJoining=true

[Alerting]

CaptchaNotificationSoundPath=captcha_notification.mp3
NumNotifications=9999
MaxNumSummonSelectionFailuresBeforePlayingSoundNotification=3
Check4SymbolsPendantsCount=false

Max4SymbolsPendantsCount=30000

**Comment by Masuzu** [comment]
I do not see anything wrong either. Usually crashes in scripts should display a message popup with details on the error. The other possibility would be that your Chrome Devtools menu crashed, which can happen if you forget to turn off the "Preserve Log" option (this got me many times in the past).
https://twitter.com/GBFPokerBot/status/1112821457309130753

**Comment by nutteda** [comment]
I always turn it off. But after try it not happen in all kind of raid.It always happen in Magna II  raids.

**Comment by nutteda** [comment]
is that normal?
![Capture](https://user-images.githubusercontent.com/49268971/55601072-26869100-5789-11e9-98f4-7b924636983e.PNG)

**Comment by nutteda** [comment]
oh it my miss understood.It doesnt crash while using skill.It crash when raid boss die  like this pic.
![Capture](https://user-images.githubusercontent.com/49268971/55602531-51c0ae80-5790-11e9-96ae-37d60500844e.PNG) it always be like this while crash

**Comment by NaoiKR** [comment]
I realized this happens when the raid boss dies too fast and your characters was using skills in the process.

Sometimes sarasa just shutdown without any error messages when this happens.

I noted that when I was using sarasa in some magna 2 content.

**Comment by ComfyEchooo** [comment]
Same issue. Is there no way to make a reboot script?

**Comment by Masuzu** [comment]
This is related to https://github.com/Masuzu/SarasaBot/issues/271
Once the shortcuts are implemented directly in Sarasa, a lot of such issues will be solved.

**Comment by Masuzu** [comment]
Sarasa Bot can now emulate key shortcuts on her own as of v2.7.0!
https://gbtools.azurewebsites.net/SarasaBot/en/Home/PatchNotes#2-7-0

The good news is that it may solve a ton of issues :) The "bad" news is that the feature is experimental. Enjoy!
