### ISSUE TITLE
error popup when trying to use kengo's rending flash 

### ISSUE THREAD

**Issue by trungpro95** [Masuzu/SarasaBot#274]
![error](https://user-images.githubusercontent.com/20255125/55855513-ed3b9000-5b91-11e9-91d0-a29d78f1c6df.png)

Script : kengo's split>flash>use all shiva's skill>lyria's buff>use 2 summons then ougi turn 1 and just attack in turn 2 and quit raid 

if booleans["assault_time"] == nil then
  if turn == 1 then
    character_1:UseSkill(2):WithWaitTime(2000)
	end
	if character_1.charge_gauge == 100 and turn == 1 then
    character_1:UseSkill(3):WithWaitTime(2000)
    --[[Use Shiva]] 
    characters["Shiva"]:UseSkill(3):WithWaitTime(1000)	
    characters["Shiva"]:UseSkill(2):WithWaitTime(1000)
    characters["Shiva"]:UseSkill(1):WithWaitTime(1000)
	Summon(1)
    --[[Use Lyria buffs--]] 
    characters["Lyria"]:UseSkill(2):WithWaitTime(1000)
	Summon(6)
  end
  if turn = 2 then
  end
  TerminateBattle()
end

**Comment by trungpro95** [comment]
So i check again and everytime it try to cast 2nd action alway lead to error

**Comment by trungpro95** [comment]
ok i make it work to the summon call part now , but the bot can't click ok on summon and try to spam back button while summon popup still up after that it show error message .

**Comment by ErogeSeiyuu** [comment]
Skill formatting changed a while ago. It's **character_1:WithWaitTime(2000):UseSkill(3)** now

There's also the weird _turn==2 then end TerminateBattle() end_ ????? 

What happens to _if booleans["assault_time"] == nil_ then? Did you set booleans up already?

```
if turn == 1 then
 if character_1.charge_gauge == 100 then
    character_1:WithWaitTime(2000):UseSkill(2)
 end
    characters["Shiva"]:WithWaitTime(1000):UseSkill(3)
    characters["Shiva"]:WithWaitTime(1000):UseSkill(2)
    characters["Shiva"]:WithWaitTime(1000):UseSkill(1)
    Summon(1)
    characters["Lyria"]:WithWaitTime(1000):UseSkill(2)
    Summon(6)
end
if turn = 2 then
  TerminateBattle()
end
```

Is this what you mean?
