### ISSUE TITLE
Reconnecting to Twitter on disconnection

### ISSUE THREAD

**Issue by Rarow** [Masuzu/SarasaBot#278]
I already set TimeLimitInSeconds=7200 or TimeLimitInSeconds=10800 but sarasa still only run for about 1 hour. And then after 1 hour, It is still checking raid and running normally but didn't do anything. it just get idle and didn't do anything.The program didn't stop or close, it just stay idle but still checking raid.

It is always happening, i can't run it for more than 1 hour, it will just stay idle after 1 hour.

Please help thank you.

**Comment by Sundaerae** [comment]
@Masuzu this happened a lot to me now. It just keep telling me 0 ongoing raid, back to trying to join raid, but there's no raid check. No 'data' from twitter. It just keep refreshing without anything like 'lv100 gabriel', for example. It's like the bot disconnected and not trying to reconnect again to twitter.

**Comment by junyong300** [comment]
Hi I also have this problem. I thought this was a Twitter account issue, but even after I signed on a developer account, I still cannot find any raid I want 
![capture](https://user-images.githubusercontent.com/12655218/58339878-7cbcaa00-7e85-11e9-90c2-e678ca4a892b.png)

**Comment by Masuzu** [comment]
There does not seem to be any correlation...
![image](https://user-images.githubusercontent.com/5464705/58344766-7f4fdd00-7e4e-11e9-8c4b-bb0d88f2e416.png)

Joke aside this will need to be addressed.

**Comment by junyong300** [comment]
Progress on this issue? or is there a fail-safe version (of both Sarasa & Chrome) I should fall back to?

**Comment by Masuzu** [comment]
Keep in mind that Twitter issues are supposed to be rare, unless you live maybe in China or similar countries with weird national firewalls.
Sarasa will now attempt to re-track raids when no raid updates have been received for too long (how much is "too long" being configurable) in v2.8.0
