### ISSUE TITLE
Sarasa won't use Soul Berries.

### ISSUE THREAD

**Issue by slashkoopa** [Masuzu/SarasaBot#279]
So every time I reach 0 ep the bot goes to the item screen, but it wont interact with the soul berries.

<code>
# The bot will stop after the given amount of soul berries (ソウルシード) are used
MaxNumSoulBerries=9999
# If you do not have a low ping, refilling battle points (BP) may induce a slight delay. In this case it may be more efficient to refill more BPs in a one go to avoid having to refill BPs for each subsequent raids.
AdditionalNumSoulBerriesToUsePerRefill=0
# The bot will stop after the given amount of soul balms (ソウルパウダー) are used
MaxNumSoulBalms=300

**Comment by slashkoopa** [comment]
![Screenshot (5)](https://user-images.githubusercontent.com/49096720/56392242-7c683800-6263-11e9-86b3-d87a3a531889.png)
picture for said problem

**Comment by justjulz29** [comment]
I have a similar problem, only it does actually select the soul berries, then sets how many to use on refill; but then it refreshes immediately as soon as it hits "Use" and then doesn't refill my BP as a result. I've been trying to work my head around how to fix it and I've had no luck...

**Comment by slashkoopa** [comment]
after updates this still occurs

**Comment by Masuzu** [comment]
Hello,
I am not sure which kind of UI extension you are using, but you should have your item layout look like this with the vanilla version of the game:
![image](https://user-images.githubusercontent.com/5464705/56864720-99b4a900-69bd-11e9-954f-192c91a2a65c.png)
