### ISSUE TITLE
SarasaBot Still won't refill BP

### ISSUE THREAD

**Issue by slashkoopa** [Masuzu/SarasaBot#281]
Anyone here is able to use BP after the updates? I'm having trouble and don't know how to use it since after going to the supplies the bot just stops at the supplies screen and it won't do any further  actions.
I don't know if I am doing anything wrong or not.

**Comment by Masuzu** [comment]
Hello,
I am not sure which kind of UI extension you are using, but you should have your item layout look like this with the vanilla unmodified version of the game:
![image](https://user-images.githubusercontent.com/5464705/56864720-99b4a900-69bd-11e9-954f-192c91a2a65c.png)
Which would then explain why refilling is not working as expected on your side.
