### ISSUE TITLE
Sarasa not responding or entering raid code

### ISSUE THREAD

**Issue by ior718** [Masuzu/SarasaBot#283]
Hello!

I have an issue with the Chrome extension. The bot is running, and it tells me to go to the quest menu. After that, the only message I get is that "Sarasa bot is calibrating", "calibrating". And I assume that I got a problem since Sarasa should be inputting raid code automatically at this point? Am I missing any steps here?

I got everything set up, in-game window size is set to medium (in JP version it's 1.5 times right?) and webpage is zoomed at 100%. Tried to reinstall extension but nothing happened.

Many thanks in advance.

**Comment by slashkoopa** [comment]
Are you using chromium instead of chrome? Apparently, chrome doesn't work for it only the old version.

**Comment by ior718** [comment]
> Are you using chromium instead of chrome? Apparently, chrome doesn't work for it only the old version.

Thanks for the timely reply. Yes, I am using the Chromium which is linked from the installation instruction page for Sarasa bot. Is there a version requirement? MY OS is windows 10.

**Comment by Masuzu** [comment]
Hello,

The version 2.5.3 adds a new debugging setting DebugCalibration.
It will display numbers in the console during the calibration step. Those should be close to 1.

A common issue is changing by mistake the type of device emulator in Chrome Devtools. This should be not be changed:
![image](https://user-images.githubusercontent.com/5464705/56864806-d03ef380-69be-11e9-8367-5029a9f7f4f7.png)
