### ISSUE TITLE
Isn't kinda the time to reduce the price of Sarasa Bot?

### ISSUE THREAD

**Issue by Qewar** [Masuzu/SarasaBot#285]
I don't wanna sound rude or anything, but I don't understand why is SarasaBot 5€ per week when ZooeyBot which has way more uses and is only 10€ a month.

Specially with the Viramate bans and strict cheat detection making the bot a bit slower and not as great as before.

**Comment by xerance** [comment]
hey, atleast it ain't as bad as the GBFCombatSniffer with 2,75euro per week.. which is ridiculous, would have given it a try if it was like max half that per month as its basically a utility addon, and you still have play yourself or buy sarasa/zooey on top of that.
