### ISSUE TITLE
Bot keeps trying to press an already used skill

### ISSUE THREAD

**Issue by executedlol** [Masuzu/SarasaBot#286]
The bot keeps trying to press an already used skill for a few tries, sometimes it does sometimes it doesn't, it's inconsistent, sometimes it also skips the next skill and just attacks, this also used to happen with Zooey Bot but with recent updates it disappeared.

[Video showing the problem](https://streamable.com/s/vyk5g?muted=1#)

I'm running the bot on a Hyper V Virtual Machine with windows 10 and latest version of Chromium (Chrome browser has the same problem), sarasabot.ini's file has the default settings and the script is just basic stuff like:

if turn == 1 then
character_1:UseSkill(1)
character_1:UseSkill(2)
characters ["Zooey"]:UseSkill(2)
end

**Comment by Sliime** [comment]
Same here, you fix it?

**Comment by executedlol** [comment]
I increased the values of all MinWaitTimeInMsAfter and MaxPageLoadDelay, bot is still slow on using skills though, there's always a 1 second downtime between skills, the bot isn't using the skill queue at all.

**Comment by Masuzu** [comment]
Hi,
This is similar to https://github.com/Masuzu/SarasaBot/issues/287
