### ISSUE TITLE
Skill Use on Raid End Crash

### ISSUE THREAD

**Issue by ComfyEchooo** [Masuzu/SarasaBot#287]
If you are using skills but the raid is killed by somebody else, the bot will close entirely. Trying to get a decent chunk of honors is typically not worth it for that reason.

There are other issues about this opened where the author suggested using viramate, but I think it's clear that is no longer viable and that a fix should be implemented ASAP. 

Using the latest version of SarasaBot and latest version of Chrome.

**Comment by DarkHorse1121** [comment]
Also faced same issue with Magna2 multi raid.
When I set lua script only attack( not using skill), crash didn't happen.
I assume that issue happen since the system change about skill.( Don't show warning message after reload. )

**Comment by Masuzu** [comment]
Viramate can still be used safely if you disable any UI overlay and keep only the combat shortcut.
I may consider adding shortcuts directly to Sarasa as well.

**Comment by Masuzu** [comment]
Sarasa Bot can now emulate key shortcuts on her own as of v2.7.0!
https://gbtools.azurewebsites.net/SarasaBot/en/Home/PatchNotes#2-7-0

**Comment by ComfyEchooo** [comment]
The emulated key shortcuts are not working. It still clicks and crashes. Viramate unpacked works as expected.
