### ISSUE TITLE
Trial expired before even started

### ISSUE THREAD

**Issue by monkeywonkey** [Masuzu/SarasaBot#29]
Hello!
I was trying out the bot today but it says expired key even though this was the first day. please help. thanks
![expiredkey](https://user-images.githubusercontent.com/34781604/34314882-a233ed34-e746-11e7-8022-0c8c8de02137.JPG)

**Comment by pcfemail** [comment]
same here

**Comment by Masuzu** [comment]
There is no free trial anymore unfortunately due to external reasons.
