### ISSUE TITLE
Emulated shortcut keys do not work.

### ISSUE THREAD

**Issue by ComfyEchooo** [Masuzu/SarasaBot#291]
Addition to #287 , Sarasa does not change any behavior when EnableShortcutKeys is to true. This causes the same problems as mentioned prior, since the bot is still clicking abilities.

Using an unpacked Viramate and toggling the UseViramate option does work to fix #287 , but it does inject HTML to show which key the skills are bound to, and I have not been able to find an option to toggle that off. This may be an unneeded risk.

**Comment by Masuzu** [comment]
Acknowledged the issue.

**Comment by Masuzu** [comment]
Update: there is currently an issue which causes the shortcuts to be ignored if EnableShortcutKeys is set to true without also setting Viramate to true. This will be addressed in the next release.

**Comment by Masuzu** [comment]
A fix was introduced in v2.8.0
