### ISSUE TITLE
Fail to obtain Raid Detail Meaning?

### ISSUE THREAD

**Issue by zappky** [Masuzu/SarasaBot#292]
Sometimes the bot respond like "Fail to obtain Raid Detail" on a newly twittered raid,which then the bot will go to gbf title screen(the one with pretty poster).  Thankfully the bot is able to continue working on the title screen,but it is just that the raid is wasted.

So why is this happening and is there anything i can do to mitigate the issue?

**Comment by Masuzu** [comment]
I can't provide all the details, but sometimes people also post "fake" raid tweets. This is such an example.
Therefore it is a non-issue.
