### ISSUE TITLE
SarasaBot Stuck Trying to Use Skill in Raid When Other Player Kills Boss 

### ISSUE THREAD

**Issue by JeremyMerkur** [Masuzu/SarasaBot#296]
This is a well known issue that you have previously refused to fix (#218 #141 #245). Given that Viramate is no longer safe/available, please fix this issue. It's a major pain to have to babysit the bot because of how frequently this crops up.

**Comment by Masuzu** [comment]
The attempts to click on the skill are not forever (at most `MaxNumRetries` should be performed) so the battle will be ended on its own after the retries finish.

**Comment by Masuzu** [comment]
Besides Viramate shortcut can now be emulated as of V2.7.0

**Comment by Masuzu** [comment]
A related updated was published in v2.10.1
