### ISSUE TITLE
Stuck on 'Pending Battles'

### ISSUE THREAD

**Issue by 0gawdn0** [Masuzu/SarasaBot#297]
Everytime I leave the bot to run for 5 minutes or so it would go to Pending battles and then just freeze there. It wont move or anything, I see SarasaBot still is finding other raids but it's not joining or doing anything and just gets frozen.

The chrome version im using is: 76.0.03809.87 Official 64 bit.

Im not sure whats making this happen.

**Comment by Masuzu** [comment]
Closing due to lack of actionable details.
https://discordapp.com/invite/JaNR87n
