### ISSUE TITLE
Invalid Twitter Credentials

### ISSUE THREAD

**Issue by XenoeJin** [Masuzu/SarasaBot#3]
I receive the error "Invalid Twitter Credentials", even though I've followed the steps exactly and made sure I had the correct keys~

**Comment by jenesis1234** [comment]
me too

**Comment by Masuzu** [comment]
Hi,

Please check your file encoding in that case:
https://github.com/Masuzu/SarasaBot/wiki/FAQ#invalid-twitter-credentials
