### ISSUE TITLE
SarasaBot crashes within 5-10 minutes of running

### ISSUE THREAD

**Issue by justjulz29** [Masuzu/SarasaBot#300]
Heya,

I've had this problem for some time with every version I've got and put up with it, but now its really gone out of hand. Sarasa Bot just crashes within 5-10 minutes of it running, not allowing me to farm properly. Is there anyone else who's had this issue before or could do a problem find for me in my settings? I just have no idea how to stop this now. Here's my Sarasa.ini file settings to look at;  

xxxxxxxxxxxxxxx

[Twitter]
RaidsToTrack=Lvl 120 Grimnir,Lv120 グリームニル
MaxNumPlayersInRaid=30
MinimumRemainingBossHpPercentage=30
MaximumRemainingBossHpPercentage=100
RaidRequestTimeToLiveInMs=900000
MinDelayInMsBeforeTryingToRejoinRaid=20000
DisplayRaids=true
TwitterTimeoutDurationInMs=20000

[General]
Language=en
MaxNumSoulBerries=9999
AdditionalNumSoulBerriesToUsePerRefill=98
MaxNumSoulBalms=9999
UseSoulBalmsWhenNoRemainingSoulBerries=true
UseSoulBalmsFirst=false
MaxPageLoadDelayInMsBeforeRetry=3500
ChromeDevToolsWindowDockedOnTheRight=true
MaxTriggerDelayInMsBeforeFallback=2300
MaxResponseDelayInMs=2000
MaxNumActionRetries=1
MinWaitTimeInMsAfterRefresh=2000
TimeLimitInSeconds=21000
UseViramate=false
OngoingRaidsCheckFrequencyInSeconds=5
WaitForRaidEndBeforeJoiningNewRaid=false

CountdownTimerHorizontalPosition=0
CountdownTimerVerticalPosition=0
FastRaidRewardCollection=false
MaximumDelayInMinutesBeforeAttemptingToRetreatFromARaid=10
QuickRaidJoining=true

[Inputs]
DelayInMsBetweenMouseDownAndUp=40
RandomDelayInMsBetweenMouseDownAndUp=20
MouseSpeed=700
MouseScrollSpeed=700.
ExitKeyCode=112
WaitTimeInMsBeforeClickInput=50

[Summons]
PreferredSummons=Kaguya,White Rabbit,Black Rabbit 
DefaultSummonAttributeTab=Misc,
RerollSummonWhenNoPreferredSummonWasFound=false

[Combat])
EnableShortcutKeys=false
EnableFpsAcceleration=true
MinWaitTimeInMsAfterAttack=500
MinWaitTimeInMsAfterSummon=3000
MinWaitTimeInMsAfterAbility=500
LuaScript=Scripts/Wanpan.lua
ReloadPageOnLastBattle=true
MaxInactivityPeriodBeforeLeavingTheRaidInMs=20000
AdditionalDelayInMsAfter2ChainBurst=1500
AdditionalDelayInMsAfter3ChainBurst=5000
AdditionalDelayInMsAfter4ChainBurst=7600
AdditionalDelayInMsAfterOverchainBurst=7600

[Debug]
Clicks=false
ForceRaidRewardCollection=false
ForceRaidJoining=false 
DebugCalibration=false

[Alerting]
CaptchaNotificationSoundPath=captcha_notification.mp3
NumNotifications=9999
MaxNumSummonSelectionFailuresBeforePlayingSoundNotification=3
Check4SymbolsPendantsCount=false
Max4SymbolsPendantsCount=30000

**Comment by ramblinguy** [comment]
I've noticed that the bot has been crashing when I turned on the keyboard shortcuts, which doesn't seem to be the case for you. What's in the lua file? Maybe try it with FPS acceleration off too

**Comment by ramblinguy** [comment]
Actually I have been noticing that it crashes more frequently than it used to. Is there any way to access the logs of whatever Sarasa is printing to the console?

**Comment by worthworth** [comment]
same here

**Comment by Masuzu** [comment]
You can start SarasaBot.exe from a console window (search for "CMD" or "Powershell" in your windows search bar) so that log messages are persisted there even after a crash.
I have a few intuitions about the recent increase in such crashes.
