### ISSUE TITLE
fatal allocation 

### ISSUE THREAD

**Issue by tidusZX** [Masuzu/SarasaBot#302]
I keep getting this after 1 attack aand the whole bot stops
![IMG-6365](https://user-images.githubusercontent.com/33868380/62847897-65b28900-bd0b-11e9-9af1-e4c16713e387.JPG)
![IMG-6366](https://user-images.githubusercontent.com/33868380/62847898-664b1f80-bd0b-11e9-98ed-64ef355e12c1.JPG)

**Comment by CorrinKrow** [comment]
recieving the same error, in v 2.11.0

Fatal error 5
Uh oh device or resorce busy:device or resource busy

Fatal eror 7
Uh oh bd allocation

**Comment by DarkHorse1121** [comment]
Also faced same issue.

**Comment by rabbit02178** [comment]
same issue

**Comment by smallqp** [comment]
Me too.

**Comment by Masuzu** [comment]
Quick update on this matter: I can reproduce consistently the case when the "Device or resource busy" errors occur in some contrived cases: the problem is clearly understood this time around.
As for the bad allocations this might be a bit trickier but we'll get down to the root cause.

**Comment by Masuzu** [comment]
"Fatal error 5" errors and similar ones indicating that a "device or resource is busy" are handled in v2.11.1.
As for bad allocation errors, they may still appear.
Should you encounter them by some unfortunate event, please report both:
- the Fatal error code
- the last console log lines

Thank you!
