### ISSUE TITLE
[2.11.1] Bot doesn't track raids properly and doesn't clear pending raids so it gets stuck in pending battles>unable to join raid loop.

### ISSUE THREAD

**Issue by devvah** [Masuzu/SarasaBot#308]
Seems like bot stops counting properly both on going raids and pending raids and focuses on joining new raids even if there are already 3 on going and while it do goes to pending raids page and click on first raid there, before page even manages to load it already switches to trying to join to new raid which brings error to check pending battles so it goes to pending battles page again clicks on first raid and before page even manages to load it already switches to trying to join to new raid.
Repeat forever until bot stops working.

On log side it just looks like this:

1)New page loaded (assist)
Failed to join raid
Refresh
New page loaded (assist)
There are pending battles
New page loaded (unclaimed)
There are pending battles which ended.
*clicks on first raid but immediately goes to*
Trying to join raid
1)New page loaded (assist)

Repeat forever until I clear manually pending raids. 

In case bot decides to visit unclaimed page while I cleared all raids already it will get stuck there doing nothing and has to be relaunched.

So bot doesn't count properly how many raids are there and switches from unclaimed page way too quick to get loot, it also doesn't focus on clearing all pending raids first before joining new batch which in case of fast dying raids during magna fest makes bot waste tons of time on error pop ups.

**Comment by Masuzu** [comment]
Thanks for the details.
I acknowleged the issue.

**Comment by Masuzu** [comment]
From recent tests it looks like an issue with your connection quality which leads to very long delays trying to load the result page when trying to claim a raid reward (I made tests with a ping of roughly 200 ms). Increasing the configuration parameter `MaxNumActionRetries` so that (`MaxNumActionRetries` times 1 second) is greater than the delay you require to have the result page loaded would solve your issue.

> So bot doesn't count properly how many raids are there and switches from unclaimed page way too quick to get loot, it also doesn't focus on clearing all pending raids first before joining new batch which in case of fast dying raids during magna fest makes bot waste tons of time on error pop ups.

Working on that.

**Comment by devvah** [comment]
While my botting laptop is medicore at best and middle eu ping doesn't help it either I think I have setup pretty generous times already because I didnt want bot to have too many action retries nor too little that bot would skip them due to raid's lenghty animations or refresh which is pretty slow on it.

```
RaidRequestTimeToLiveInMs=7000 (I changed it today from 10000)
# Sometimes, Sarasa won't join a raid because the remaning HP percentage of the boss does not meet the criterion defined by MaximumRemainingBossHpPercentage. In this case, the raid will be queued for later and Sarasa will attempt to join it again if there are no other raids to join. Values are given in milliseconds.
MinDelayInMsBeforeTryingToRejoinRaid=10000
DisplayRaids=false
# Sarasa will attempt to track again raids if no raid updates were received after that duration. Values are given in milliseconds.
TwitterTimeoutDurationInMs=20000
```

```
MaxPageLoadDelayInMsBeforeRetry=7500
# Maximum amount of time Sarasa will wait for an expected event to occur (for instance, the attack button appearance) before triggering the fallback policy.
MaxTriggerDelayInMsBeforeFallback=5000
# Maximum delay before an action is deemed to have failed due to a lack of response from the GBF servers
MaxResponseDelayInMs=5000
# Maximum number of retry attempts when an action fails (due to a lack of response for instance) before the fallback policy kicks in
MaxNumActionRetries=2 (also changed from 1)
MinWaitTimeInMsAfterRefresh=3000
```

However due to typhoon today wasn't as crazy with raids as yesterday so most of the day bot worked properly and only once unclaimed loop happened.

Since I'm using that laptop exclusively to bot and discord when not botting I can surely say that nothing changed on laptop and these loops werent happening for sure in 2.8.0

I will test ver 2.11.2 tomorrow when I have more time.
