### ISSUE TITLE
does not refill the EP

### ISSUE THREAD

**Issue by readmynameplease** [Masuzu/SarasaBot#315]
tried multiple troubleshooting and still the EP refill seems to stop the bot from working properly that's all everything else is so good

**Comment by readmynameplease** [comment]
Up!

**Comment by readmynameplease** [comment]
Up!

**Comment by readmynameplease** [comment]
up

**Comment by Mewnya** [comment]
For some reason this one is a tough nut to crack.

**Comment by Mewnya** [comment]
Addressed in [v2.13.3](https://gbtools.azurewebsites.net/SarasaBot/en/Home/PatchNotes#2-13-3)
