### ISSUE TITLE
enemy_1.GetHp() and enemy_1.GetHpPercentage() seems to crash SarasaBot without any error message

### ISSUE THREAD

**Issue by ramblinguy** [Masuzu/SarasaBot#316]
The bot exits right when it reaches this line in the code. According to this page: https://github.com/Masuzu/SarasaBot/wiki/Lua-scripts
These two commands should check for the hp continuously. My usage case is that I am currently waiting for Omega 2s to drop below 40% and lose their elemental resistance. I am on sarasabot 2.13.3.

This was tested on Chrome 80.0.3987.149 64 bit.

**Comment by Mewnya** [comment]
It sure does as there is a slight syntax error.
Those are methods so you need to use a `:` instead of a `.`
