### ISSUE TITLE
Sometimes the bot isn't able to click a skill due to the Raid/Combat log blocking the clicks, is there a way to bypass this?

### ISSUE THREAD

**Issue by Qewar** [Masuzu/SarasaBot#318]
Talking about this specifically, 

![Capture](https://user-images.githubusercontent.com/50082459/78615025-3dfacd00-7868-11ea-9c55-8c49b586f7a8.PNG)

but instead of "X character made a double attack" it's "X boss has gone in overdrive mode"  and it happens when using skill/summons

It's a bit annoying on raids that go down quickly as there's 2~3 popups that end up blocking clicks at some point and I don't think there's an option to turn it off

**Comment by Mewnya** [comment]
Everyone has to live with this. Anything trying to bypass those limitations can be identified depending on how much effort  "they" are willing to put.
Those are not an issue unless you are referring to phase transtions which can last a long time and prevent you to perform actions.
More complex raid scripts on a case by case basis, for instance using `enemy_1:GetHpPercentage()` to check the boss HP periodically after each action and detect those phase transitions, followed by a `Refresh`, can be used to cut that wait time.
We leave it to the users to exert good judgement in these cases!
