### ISSUE TITLE
Bot not using soulberries

### ISSUE THREAD

**Issue by Jagger0083** [Masuzu/SarasaBot#32]
I'm not 100% sure if it's a mistake on my part but whenever my ep is depleted the bot attempts to use soul balms instead of berries which causes is to stop since I have it set to not use soul balms. Here are my settings

[General]
# Possible values: jp, en. Default to en when the string is malformed. Please make sure that your configuration file is encoded using UTF8 if you use non Unicode characters.
Language=en
# The bot will stop after the given amount of soul berries (ソウルシード) are used
MaxNumSoulBerries=9999
# If you do not have a low ping, refilling battle points (BP) may induce a slight delay. In this case it may be more efficient to refill more BPs in a one go to avoid having to refill BPs for each subsequent raids.
AdditionalNumSoulBerriesToUsePerRefill=80
# The bot will stop after the given amount of soul balms (ソウルパウダー) are used
MaxNumSoulBalms=0
UseSoulBalmsWhenNoRemainingSoulBerries=false
# Set this paramter to true to use soul balms (ソウルパウダー) instead of soul berries (ソウルシード) in priority 
UseSoulBalmsFirst=false
# ChromeDevToolsWindowDockedOnTheRight should be set to false if your Chrome DevTools console is docked on the bottom (as seen here https://i.imgur.com/bvTOq0g.png), and to true if it is docked on the right
ChromeDevToolsWindowDockedOnTheRight=false
MaxPageLoadDelayInMsBeforeRetry=3500
# Maximum amount of time Sarasa will wait for an expected event to occur (for instance, the attack button appearance) before triggering the fallback policy.
MaxTriggerDelayInMsBeforeFallback=5000
# Maximum delay before an action is deemed to have failed due to a lack of response from the GBF servers
MaxResponseDelayInMs=2500
# Maximum number of retry attempts when an action fails (due to a lack of response for instance) before the fallback policy kicks in
MaxNumActionRetries=2
MinWaitTimeInMsAfterRefresh=2000
# The bot will stop after the given parameter no matter what.
TimeLimitInSeconds=6000
UseViramate=true

**Comment by Masuzu** [comment]
Hi,
It does work fine unless you ran into a lag spike.

**Comment by tokyygranblue** [comment]
This is happening for me as well when the bot goes to refill.
