### ISSUE TITLE
Proposal: Alarm the user when the app could not detect any incoming raid after some time

### ISSUE THREAD

**Issue by nobody0014** [Masuzu/SarasaBot#34]
So the issue is that after awhile twitter started to go crazy or my internet start being shiite (this issue is not sarasa fault) and we get no raids detected.
It would be nice if we are alarmed that there have been no raids detected after awhile so that we can go back and restart the bot (this is so that i dont have to keep looking at the bot every 15-30 minutes).

**Comment by kenzi333** [comment]
I got this issue also i doubt its got to do with internet. Its likely either twitter is crap or something bugged the bot. I get this issue every 20 minutes. Its so annoying that pretty much no different to sitting next to computer and waiting for raids. Really hope there is a fix to this

**Comment by cobeng13** [comment]
Did you try to extended the waiting time setting MaxResponseDelayInMs

**Comment by kenzi333** [comment]
Yes i did. Is there an amount to increase so it doesnt bug out?

**Comment by Masuzu** [comment]
I have a constant feed of new raid IDs on my side even if I leave the bot for more than 12 hours on, over the whole night for instance.
