### ISSUE TITLE
Having issues with lua scripts while running Sarasabot

### ISSUE THREAD

**Issue by SnakeLegend** [Masuzu/SarasaBot#35]
![untitled](https://user-images.githubusercontent.com/34377079/34384417-fcdf74c4-eb56-11e7-9884-317de491c1a0.png)

This happened once in awhile, but once it happens, it happens often, which i had to restart my pc to get things working normal again.

Otherwise, the other time i had a bot.exe stopped working issue too.

**Comment by agesa** [comment]
This seems to be tied to refreshing, turning that off should stop it for now.

**Comment by SnakeLegend** [comment]
Ok that solved the problem actually, thanks!
