### ISSUE TITLE
Sarasabot Twitter application

### ISSUE THREAD

**Issue by alexander997** [Masuzu/SarasaBot#36]
![unbenannt](https://user-images.githubusercontent.com/35029824/34482227-f7394e5a-efb6-11e7-950e-b014a2b32c83.png)
![unbenannt](https://user-images.githubusercontent.com/35029824/34482235-ff4625fa-efb6-11e7-9ae7-bb5584b1cb3e.png)

what exatly do i have to create? what should be the website url ?.. because i get invalid twitte rcredentials message from sarasa bot. i created twitter application with my twitter url i have put acces key and so on. help me please

**Comment by alexander997** [comment]
nvm this

**Comment by nut11443366** [comment]
I have a same question lol

**Comment by nut11443366** [comment]
I did a SarasaBot.ini to be an UTF-8 already but it still show  "twitter invalid credentials" to me so I don't know what do I have to do so please help me

**Comment by jojosong17** [comment]
just asking how did you solve this problem？

**Comment by alexander997** [comment]
redownload the bot and open with notepad++ only. also it doesnt matte what is put in twitter applician just try to reroll your twitter keys and put it in the ini. cant help pc broke

**Comment by Masuzu** [comment]
Hi,
Please check this your file encoding: if UTF8 does not work use UTF8 without BOM:
![image](https://user-images.githubusercontent.com/5464705/34677180-8faa242a-f48f-11e7-9296-62f455be7b67.png)
