### ISSUE TITLE
Stuck on wipe-out

### ISSUE THREAD

**Issue by Einhalkzt** [Masuzu/SarasaBot#37]
somehow the bot stuck if everyone is dead even if the raid finished after a while, it'll just stack there with the salute button. is there anyway to prevent this? or is it possible to do a check, if mc die terminatebattle or something?

**Comment by Masuzu** [comment]
Hi,
This is a situation I am aware off.
I will do something about it this week.

**Comment by Masuzu** [comment]
Fixed in v1.4.0
https://poker-bot.azurewebsites.net/SarasaBot/en/Home/PatchNotes#1-4-0
