### ISSUE TITLE
Failed to select character

### ISSUE THREAD

**Issue by aysien** [Masuzu/SarasaBot#39]
![bot](https://user-images.githubusercontent.com/31809167/34675783-febd4ba6-f4cd-11e7-9b73-50a9e63dd458.jpg)

Hi, Im using zooey bot also so I know how to program the script.
But in sarasa Bot my bot always stuck in this part. 
They failed to select the character and stay still even when raid is finish. 
And its random. Sometimes it failed to select the first character.
Could you fix this?

**Comment by Masuzu** [comment]
Hi,
This issue is specific to non Viramate users and results in the bot getting stuck when the battle already ended (please do correct me if I am wrong). I will try and see what can be done about this.
The fact that the battle end was not detected properly is somewhat problematic.

**Comment by aysien** [comment]
I see...
I set the min raid HP to 5% and max at 90%.
The main reason is I don't want the bot to wait for 3 raids at the same time too long. So I set the min HP so low. As a precaution, I will set the raids min HP higher for a while until you fix it.

**Comment by Masuzu** [comment]
By default, there will be a wait time of `MinWaitTimeInMsAfterAbility` after casing any ability. For skills which take a long time to cast or when the boss enters the break/overdrive state, you will sometimes notice a significant increase in delay before you can take the next action. You should use:
`characters[XXX]:WithWaitTime(YYY):UseSkill(AAA)` in those cases.

**Comment by aysien** [comment]
I set it like this
`character_1:WithWaitTime(2000):UseSkill(2)`
`character_4:WithWaitTime(4100):UseSkill(2)`
`character_4:UseSkill(2)`

After I MC do Bounty, I give a wait time.
After that zooey in row 4 Failed to select character.

But after i do some research about this once more, 
no one post this bug except me so probably on Sarabot.ini file.
Probably the problem is because I set 
`# Maximum number of retry attempts when an action fails (due to a lack of response for instance) before the fallback policy kicks in`
`MaxNumActionRetries=0`
Because the `MaxNumActionRetries=0` the bot wont repeat the failed action then the bot stop.
What do you think?

**Comment by Masuzu** [comment]
Ah it is used internally indeed. I set it to 2 on my side (as provided in the default configuration file) and use Viramate. It saves a lot of trouble sometimes with skill/summon use.
