### ISSUE TITLE
WTF

### ISSUE THREAD

**Issue by jenesis1234** [Masuzu/SarasaBot#4]
I bought 1 month plan today, but Expiration date is 12/9/2017 8:15:42 AM.
FIX PLEASE.

**Comment by mawile0816** [comment]
I have same issue.

**Comment by Masuzu** [comment]
There is NO 1 month plan.

**Comment by mawile0816** [comment]
In the Account page, there’s 1month plan

So I understand you dont have 1 month plan... but we totaly thought it is 1month plan and we already bought it...
Please don't just deny… and check your page before replying ;(
https://i.gyazo.com/dd5f267e79cc304c0b65c98e12ad6557.png
