### ISSUE TITLE
Sarasa can't use Reroll summon.

### ISSUE THREAD

**Issue by meteoshower** [Masuzu/SarasaBot#42]
Hi masuzu i have some problem about #RerollSummonWhenNoPreferredSummonWasFound 
i set it to true. when in case sarasa go to Test Machina Alpha Window but she dont pick any summon and 
back to http://game.granbluefantasy.jp/#quest/assist .When She found new raid she still join raid and dont found summon preferred  then back to  Test Machina Alpha again and dont reroll summon.  hope you fix this . thank you

**Comment by Masuzu** [comment]
Hello,
Ah, thank you for reporting this.

**Comment by Sundaerae** [comment]
bump
because the bug isn't fixed yet.
