### ISSUE TITLE
Sarasa bot stuck at quest results

### ISSUE THREAD

**Issue by executedlol** [Masuzu/SarasaBot#43]
I don't know what's causing this but, after 20~30 minutes the bot gets stuck in the quest results ("there isn't any loot you can collect from this battle") and it just loops between the page http://game.granbluefantasy.jp/#quest/assist and game.granbluefantasy.jp/#raid_multi/xxxxxxx nonstop.

Video here: https://youtu.be/8W4SsIqIFAM?t=1s (starts happening at ~2:30 mins

**Comment by meteoshower** [comment]
i'm confirm this problem so i found this case too.

**Comment by Masuzu** [comment]
Thank you for reporting this.

**Comment by Masuzu** [comment]
Oh, actually the issue is due to Sarasa still thinking that the combat mode is active.

**Comment by Masuzu** [comment]
It is a very, very rare case, hence I will rescore this issue with a low priority.
