### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by tidusZX** [Masuzu/SarasaBot#45]
It was working fine till yesterday but today when I started it up it said I was an unregistered user but my license is still active. I've tried updating the serial number and key file multiple times but it still doesnt work. Thanks for the help

**Comment by Masuzu** [comment]
Hello,

Please check https://github.com/Masuzu/SarasaBot/wiki/FAQ#i-get-an-unregistered-user-error-message
It is working fine.
I have just been running the latest version on a brand new computer.
