### ISSUE TITLE
How to TerminateBattle if wiped?

### ISSUE THREAD

**Issue by Sundaerae** [Masuzu/SarasaBot#46]
I tried
if (character_1 == nil) and (character_2 == nil) and (character_3 == nil) and (character_4 == nil) then
TerminateBattle()
end

but it doesn't work
Or can you add a flag into the config for 'go back to raid selection screen' instead of waiting?

**Comment by Masuzu** [comment]
Hello,

Thank you for reaching out.
For now you can do something like:
```
local num_characters_alive=0
for name, character in pairs(characters) do
  if character.hp > = then
    num_characters_alive = num_characters_alive + 1
  end
end
if num_characters_alive == 0 then
  TerminateBattle()
end
```
I will make this feature easier in the future.

**Comment by Masuzu** [comment]
Sarasa will now automatically terminate the battle if the party wiped.
