### ISSUE TITLE
Network error

### ISSUE THREAD

**Issue by breinjhel** [Masuzu/SarasaBot#49]
Sometimes when using the bot Im getting a network error popup from gbf and the bot stops working when that appears. It should just close that popup and continue. Im guessing that popup occurs since theres a lot of clicking and network requests in a short amount of time

**Comment by Masuzu** [comment]
When does this popup appears? Sometimes it is just transient, and most of the time is caused by Internet connection issues. Therefore I do not plan to start adding workarounds for this kind of abnormal behaviour : if I would start going in this direction things will get very messy.
