### ISSUE TITLE
Different serial number for sarasabot, zoibot and casino bot?

### ISSUE THREAD

**Issue by ErogeSeiyuu** [Masuzu/SarasaBot#51]
I want to use sarasabot on my main desktop instead of my laptop - which is dedicated to only zoibot and casinobot. But when I tried to change serial number, zoibot and casinobot's serial number got changed as well. Can you either fix that issue or decreases the time needed to change serial number since it's GW and i need to run zoibot on my laptop?

tl;dr: It would be great if sarasabot, zoibot and casinobot use different serial number.

**Comment by Masuzu** [comment]
I am not sure if I'll have such a thing, but I took note of this.
