### ISSUE TITLE
Bot stuck after battle with "Failed to retrieve the charge attack button status" error

### ISSUE THREAD

**Issue by Hedova928** [Masuzu/SarasaBot#55]
After a battle ends, sometimes SarasaBot shows "Failed to retrieve the charge attack button status" and gets stuck, rather than "Move to result page", even though the result page has been loaded.

![image](https://user-images.githubusercontent.com/35021122/35310973-0c26e9ae-0069-11e8-98c8-0873e9ec3ef3.png)

**Comment by Masuzu** [comment]
Hello,

Ouch, did you happen to have a DisableChargeAttack or EnableChargeAttack in your script?

**Comment by Hedova928** [comment]
Yes, both. I disable it at the start of a turn and turn it on depending on the characters' charge gauges.

**Comment by Masuzu** [comment]
Ah I see, thank you.
Issue addressed in v1.6.0
https://poker-bot.azurewebsites.net/SarasaBot/en/Home/PatchNotes#1-6-0
