### ISSUE TITLE
Sarasabot is talking to me

### ISSUE THREAD

**Issue by xFilesx** [Masuzu/SarasaBot#57]
I bought the licence awhile ago, and had no issues running the program for hours yesterday, however today, it was running smoothly till sarasabot started 'talking' to me with some phrase over and over. the volume origin is from sarasabot, is this a feature or am i going crazy.

**Comment by Masuzu** [comment]
LOLWUT

**Comment by xFilesx** [comment]
hey so, im not trolling, I figured out what the mp3 was, it was the
'captcha' notification, I hadnt received it before, and when I looked at th
epage, no captcha was there (i didnt know at the time it was the noise for
the captcha) and it was just repeating its phrase while still leeching
raids. somehow the error was created while it was leeching on my browser
but i do not know what could have set it off if it wasnt the captcha gbf
gives you.
