### ISSUE TITLE
Cannot run the extension / SarasaBot

### ISSUE THREAD

**Issue by koqiman40199** [Masuzu/SarasaBot#58]
Hello,

I encounter some problems here. Could you please give me some advise?
1. After install Sarasa extension and click Start button, then nothing happen.
2. SarasaBot always tell me to change ChromeDevToolsWindowDockedOnTheRight which i have already changed to True.
3. Invalid twitter credential always popup after running SarasaBot
![untitled](https://user-images.githubusercontent.com/35824770/35422422-2de9de5c-027b-11e8-9419-9c9dc3200cd0.png)

Running on:
Windows 10
Chrome Version 63.0.3239.132 (Official Build) (64-bit)

**Comment by koqiman40199** [comment]
Ok, solved now

1. After install Sarasa extension and click Start button, then nothing happen.
- Everything works fine after solving 2 problems below

2. SarasaBot always tell me to change ChromeDevToolsWindowDockedOnTheRight which i have already changed to True.
- Solved, Close What's New tab and everything is good to go

3. Invalid twitter credential always popup after running SarasaBot
- Solved, Change SarasaBot.ini file to UTF8

**Comment by Masuzu** [comment]
Hello,
That is great that you managed to get those issues sorted on your own!
