### ISSUE TITLE
Combat stuck on error trying to use ability on paralyzed character

### ISSUE THREAD

**Issue by Hedova928** [Masuzu/SarasaBot#61]
When a character is paralyzed or otherwise unable to use skills the bot sometimes gets stuck on the error message.

![image](https://user-images.githubusercontent.com/35021122/35520348-9d956576-04cb-11e8-9973-1acb6b11f415.png)

![image](https://user-images.githubusercontent.com/35021122/35520013-b04fcc84-04ca-11e8-8d68-203c916ff62a.png)

**Comment by Masuzu** [comment]
Addressed in last versions
