### ISSUE TITLE
1.6.1 Twitter No Response

### ISSUE THREAD

**Issue by MillionRice** [Masuzu/SarasaBot#64]
There is a same problem to me. The twitter raids wont pop up like usual after running the application. I also tried the version 1.5.0, but its just the same problem like 1.6.1. I wonder maybe there is something run with the twitter part?

> After updating from v1.6.0 to v1.6.1 with all remaining files in order, it cannot go past the red text "Please check the configuration parameter ChromeDevToolsWindowDockedOnTheRight..." with no other cues.

And after I press Start, it will say Good to go, but nothing will happen then.

**Comment by DarkenShade** [comment]
I also have this problem. 

i got the product yesterday and tried 1.6.1 but it would not say or do anything past "good to go" and did not list any raids. 

i then went to 1.5.1 and it worked perfectly. 

today when it was updated to 1.6.2, 1.5.1 stoped working so i tried to use 1.6.2 and it has the same problem as 1.6.1

**Comment by Masuzu** [comment]
Hello,

This issue is related to https://github.com/Masuzu/SarasaBot/issues/65
I will address it in the day and provide compensation.
