### ISSUE TITLE
SlimeBlast Mode Bug 

### ISSUE THREAD

**Issue by Goreeng** [Masuzu/SarasaBot#66]
Hey, i keep getting this problem when im using the Slave bot (For slime blasting), it always redirect me to my homepage after i pressed "Enter"
I have followed every step in the documentation, can you help?

https://imgur.com/a/F3MtA

**Comment by Masuzu** [comment]
Hello,
It could be due to this: https://github.com/Masuzu/ZooeyBot/issues/421
