### ISSUE TITLE
Request Coop Raid.

### ISSUE THREAD

**Issue by meteoshower** [Masuzu/SarasaBot#68]
Hello Masuzu san is it possible in the future to join round robin co-op raid .
As i know some raid like  Ubaha normal Or other raid in coop raid have chance to win and faster than tweet join .  e.g. I choose some room round robin and then active sarasa to runscript and when raid end may be have sound alert. thanks Masuzu

**Comment by Masuzu** [comment]
Hello,
This feature is not available for now but that is a very good suggestion. However, other priorities await first.
