### ISSUE TITLE
Both bots have same ID by default

### ISSUE THREAD

**Issue by agesa** [Masuzu/SarasaBot#7]
While ZooeyBotExtensionIdGenerator.exe solves everything, anyone who hasn't run that once will probably be confused for a few minutes when loading one extension into Chrome overwrites the other one.  Is it possible to give them different default IDs?

**Comment by Masuzu** [comment]
I can't reproduce the issue.
I can load both extensions and each has a different ID. There is no such thing as a default ID.

**Comment by Masuzu** [comment]
Addressed in v1.2.0: https://poker-bot.azurewebsites.net/SarasaBot/en/Home/PatchNotes#1-2-0
Thank you again for reporting this issue.
