### ISSUE TITLE
 Do not load Twitter's Relief ID in version 1.7.1

### ISSUE THREAD

**Issue by kusyarudaora123** [Masuzu/SarasaBot#70]
Hello.
In version 1.6.3 I was reading the relief ID, but version 1.7.1 did not load the relief ID.
I chose UTF 8 or UTF 8 without BOM in encoding, but it did not load.

![1](https://user-images.githubusercontent.com/36522930/36286516-7dc82388-12f3-11e8-9408-18d915e68c8d.jpg)
![2](https://user-images.githubusercontent.com/36522930/36286519-816da9c2-12f3-11e8-893d-c89a9b06c4de.jpg)

**Comment by Masuzu** [comment]
Hello,
I found what the issue was. Nothing you can do for now however. A fix will be released within the next 12 hours as well as a form of compensation.

**Comment by kusyarudaora123** [comment]
thank you!
