### ISSUE TITLE
No Raids Found Issue

### ISSUE THREAD

**Issue by IZEROII** [Masuzu/SarasaBot#71]
@Masuzu 

I have attempted to look through the closed issues but I can not seem to discover my issue.  I'm a long time ZooeyBot user but can't seem to make this one work. 

I solved the twitter authentication issues as it was an error on my end.  I establish execution of the bot the same as Zooey and get the "Good to Go" dialogue prompting me to click on Quest button.  This is where my issue begins.

It brings up the raid selection page but continues to tell me there are 0 raids found and endlessly refreshes.  An issue you addressed in #50 .  

My parameters for Chev are as such 
![untitled](https://user-images.githubusercontent.com/24773141/36293163-2d60c8b2-12a5-11e8-9f5b-bb1ac6517c26.png)

And like in #50 it continuously says there are 0 raids found even when on screen there are raids that to what I think match the parameters above.  I assume the bot is pooling beyond what 5 raids are visible on screen? Like tweetdeck or any raid finder. 

My twitter app has the same permissions that you addressed in another post.  I just filled in bogus information for the requested sections when establishing the app but don't think that has anything to do with it.  

Any help from you or the community would be great so I can continue to fund this service.

**Comment by nut11443366** [comment]
I think newest version has a problem so I recomend to  use the old one

**Comment by Masuzu** [comment]
Hello,o
I will look into it.

**Comment by Masuzu** [comment]
I found what the issue was. Nothing you can do for now however. A fix will be released within the next 12 hours as well as a form of compensation.

**Comment by IZEROII** [comment]
Thank you for your attention sir

**Comment by cobeng13** [comment]
Oh, I just renewed for 6 hours. Was unlucky this time

**Comment by Masuzu** [comment]
This is now addressed in v1.7.2.
Good luck with your first GW round.
