### ISSUE TITLE
I got a "Failed to join the raid" error message.

### ISSUE THREAD

**Issue by arc002** [Masuzu/SarasaBot#73]
When participating in three RAIDs, a large number of error messages "Failed to join the raid" will be displayed.
By checking with the Chrome DevTools, Chrome is sending a lot of requests.(battle_key_check?～)

**Comment by Masuzu** [comment]
While it won't cause Sarasa to completely stop, until one of the 3 raids clears, I took the note of the issue and will do something about it in a future release.

**Comment by Masuzu** [comment]
This is now addressed in v1.7.3.
https://poker-bot.azurewebsites.net/SarasaBot/en/Home/PatchNotes#1-7-3
Happy hunting.

**Comment by Kasenff** [comment]
Still having this problem
