### ISSUE TITLE
Sarasa Bot automatically turn off itself and Devtool

### ISSUE THREAD

**Issue by zodiark2078** [Masuzu/SarasaBot#74]
I came across the situation when sarasa bot run for around 20 mins, its will turn off itself and devtool without any notification. When observing, i see that the situation happened a lot when i joined 3 raid and waiting for a long time ( about 4 mins ) before any of 3 raid finished to find another raid. What can i do to stop this problem?
Thank you for your bot, it helps me a lot :D.

**Comment by Masuzu** [comment]
Hello,
It is related to https://github.com/Masuzu/SarasaBot/issues/73.
I will release an update today or tomorrow.
