### ISSUE TITLE
Terminate Battle when wiped isn't working

### ISSUE THREAD

**Issue by Sundaerae** [Masuzu/SarasaBot#75]
I haven't test this since last time you closed my thread about terminating battle. The exact quote is "Sarasa will now automatically terminate the battle if the party wiped." on 29 Jan.
It doesn't work, the bot will still stuck on the 'boost skill/def/etc' pop up and not terminating the battle.
The hotfix from a month ago:
`local num_characters_alive = 0
for name, character in pairs(characters) do
  if character.hp > 0 then
    num_characters_alive = num_characters_alive + 1
  end
end
if num_characters_alive == 0 then
  TerminateBattle()
end`
also doesn't work since the bot didn't register it as new turn so it didn't read the script.

**Comment by Masuzu** [comment]
Party wipe detection works fine on my side and the battle is stopped when it happens after the turn ends after the page is reloaded.
Could you post the messages in your console should it happen again please?

**Comment by Sundaerae** [comment]
ok I have renewed my license.
the bot basically stuck here. Can't you make it so the bot just terminate when it sees the salute button?
sometimes, only sometimes though, the bot can proceed after the raid is done. IF, it's done.
Maybe you can say one of the solution is MaximumDelayInMinutesBeforeAttemptingToRetreatFromARaid.
I dunno what counts MaximumDelayInMinutesBeforeAttemptingToRetreatFromARaid. If I say 10 minutes, is it
1) 10 minutes from the raid start? 
2) 10 minutes from when the bot first join? 
3) 10 minutes since the last action? it's pretty ambiguous.
If it is the 1st one, what happened when I join raid that already below 1 hour left?
if it the 2nd and 3rd one, that would make me retreat even though my team is not wiped yet.

![stuck](https://user-images.githubusercontent.com/31296536/37073488-dd437244-21f9-11e8-986e-334705980e03.png)

**Comment by Sundaerae** [comment]
The script used is pretty standard stuff.  The number of characters checker doesn't work since the bot stuck on some state before reading the script.

local num_characters_alive = 0
for name, character in pairs(characters) do
  if character.hp > 0 then
    num_characters_alive = num_characters_alive + 1
  end
end
if num_characters_alive == 0 then
  TerminateBattle()
end
if not (characters["Zooey"] == nil) then
characters["Zooey"]:UseSkill(2)
end
character_1:UseSkill(2)
character_1:UseSkill(3)

**Comment by YumeHaru** [comment]
Bump
I just met the same problem, bot doesn't auto terminate battle after party is wiped.
Tested with chronium.

**Comment by Masuzu** [comment]
This particular issue, namely ending the battle after a party wipe, was addressed in a previous version. No regression with the last version so far regarding this feature.
