### ISSUE TITLE
SarasaBot won't open pending battle

### ISSUE THREAD

**Issue by Zemaya** [Masuzu/SarasaBot#76]
For some reason my SarasaBot won't clear my pending battles and let them just pile up until I can't join raids anymore.

I tried the fast raid collection option but it still didn't work.

I'm using sarasa bot v1.7.3 and google chrome canary v66 because v64 gave me a really bad memory leak.

**Comment by Masuzu** [comment]
I will investigate after today's reset.

**Comment by RabbitRyu** [comment]
Hello Masuzu,
I am having the same problem.
Is it possible to extend or refund the term?

**Comment by Masuzu** [comment]
I am not sure what you mean, it is working fine on several different computers used for tests.
After some ongoing raids battle, "There are pending battles" will be displayed in the console and Sarasa will move to the unclaimed quests page, proceeding to claim the rewards.

**Comment by Zemaya** [comment]
My Sarasa moved to the unclaimed quests page but never clicked on any of the pending battles. It just stuck there and keep trying to enter another raid, getting stuck in a loop.

I'll try with another raids for a while and report the result.

**Comment by Zemaya** [comment]
It's still looping, it knows that it being blocked by pending battles yet it can't detect any.

I made a video of the loop, maybe there's a problem with my setting.

https://youtu.be/fmBKOOhcDHk

**Comment by Masuzu** [comment]
Thank you, I will see what I can do.
I use these Viramate settings when automating things:
![image](https://user-images.githubusercontent.com/5464705/36964431-e851ee94-2056-11e8-82ad-6ca09fa61bb0.png)
![image](https://user-images.githubusercontent.com/5464705/36964437-ef78dade-2056-11e8-9ce4-58113b2b1d04.png)
(The other settings are unrelated).

**Comment by Masuzu** [comment]
Do you happen to have error messages in the DevTools console tab when the issue happens?
I will release another version today with more information in the console.
Also, if you are fine with it, I can provide a compensation if you send me the email or serial number bound to your account to sarasa-bot-support@azuriteworlds.com
It is the first time I have someone report this issue but it is a blocking one indeed.

**Comment by Zemaya** [comment]
Our viramate setting is pretty identical with a few differences: I turned on the buff/debuff timer and turned off the turn counter.

I'm using mobage account. Sadly I don't have a recording of the DevTools console tab for now.

I have a hunch that the problem is because of the google chrome canary, I checked a bit and it have a problem with multiple battle quests detection and always trying to check at the result page by battle 2.

It worked well with normal google chrome, but the memory leak is so bad on the newest version of chrome (v64) it will always got paused by debugger every 15 minutes or so, thus I can't really check if it's working as well as intended.

I won't have access to my laptop for a few days so I won't be able to make a recording of the devtools, but I'll try to downgrade my chrome version and see how it goes.

I have sent you an email.

**Comment by Masuzu** [comment]
Oh, you are using the Google Canari pre-release version. I have no plan to support this not yet fully production-ready version and will only cater for the official Google Chrome build (`Version 64.0.3282.186 (Official Build) (64-bit)` as of now, which I used to test on several different computers).
Did you try disabling the sound settings and using Lite settings? The RAM usage of Chrome should not exceed 2.5 GB.
Make sure to use the Beta version settings as well or expect a noticeable performance degradation even with a high end computer:
![image](https://user-images.githubusercontent.com/5464705/36996967-710ff71a-20b8-11e8-9347-b49995472e39.png)

My Network tab looks as follows:
![image](https://user-images.githubusercontent.com/5464705/36996723-c7305b36-20b7-11e8-8b62-256356e5d1f5.png)
As for the source tab, some people reported that disabling breakpoints could avoid the Chrome debugger stopping:
![image](https://user-images.githubusercontent.com/5464705/36996879-2bec226c-20b8-11e8-8306-2daf34071706.png)

I will make some changes in the next release but can't promise anything.

**Comment by Masuzu** [comment]
Try with the new version and setting the new parameter ForceRaidRewardCollection to true.

**Comment by Zemaya** [comment]
It's working fine now, thanks!
