### ISSUE TITLE
Problem with purchase

### ISSUE THREAD

**Issue by Kasenff** [Masuzu/SarasaBot#77]
I made too many purchases cause the browser gave me an error when I tried to purchase it. Now I have 4 Transactions. T-T

Please help
 https://i.imgur.com/MlBvWQ6.png @Masuzu

**Comment by Masuzu** [comment]
Hello,
I can see if I can revert the additional transactions. Could please send to sarasa-bot-support@azuriteworlds.com the email or serial number bound to your account?

**Comment by Masuzu** [comment]
Addressed.
