### ISSUE TITLE
Still have problem regarding with automatically turn off sarasa bot

### ISSUE THREAD

**Issue by zodiark2078** [Masuzu/SarasaBot#79]
Hi. I have downloaded the lastest version of sarasa bot and its seem that i can't use it more than 40 mins.
Still have the same problem related with Issue #74 . Can you double check it please. Thanks in advance :D

**Comment by Masuzu** [comment]
Hello,
If it "automatically" turns off the only answer I can give is intermittent connection issues (I had the same happen a few months ago due to DNS issues on my side).

**Comment by zodiark2078** [comment]
I'm quite sure my internet connection is stable ( i'm often playing dota 2 while using sarasa bot. Also i used zooey bot for 2 hours after that without any problem related to internet. ). I just notice that if i  don't stuck in 3 raids situation more than 2 mins, sarasa bot will stay longer than usual.

**Comment by CorrinKrow** [comment]
Hi, I am also experiencing the same problem, and my internet connect is also fairly stable. Like zodiark this issue seems to only occur when there are 3 ongoing raids.

**Comment by zodiark2078** [comment]
Solved the problem by downgrading your google chrome to version 61 and everything works fine. I think sarasa bot might not compatible with chrome version above 63. Haven't test version 62 btw.
