### ISSUE TITLE
Various problems

### ISSUE THREAD

**Issue by SeraphimEx** [Masuzu/SarasaBot#80]
Good day!
just bought a 6 day license earlier.
having various problems.
Haven't been able to even do successfully one run.
It gets stuck on the results screen after a raid.
It gets stuck on the no loot screen when a raid gets killed before im able to contrib.
It doesnt seem to do anything after TerminateBattle()
Sometimes it gets stuck on the summon select screen.
Sometimes it shows a popup saying something like "Selecting an empty summon tab shouldnt happen".
Most of the time when it's stuck the pointer is hovering in between where the home and menu buttons lie on top of the game.
Ive tried reinstalling, double checking my resolutions, and i also tried on different pc's(my laptop).

*Edit: Got it to run by going windowed

*New problem: Every like 2-6minutes of running the developer tab gives this pause thing 
says "Cannot read property 'params' of undefined"

**Comment by Masuzu** [comment]
Hello,
I am afraid that it looks like you fall in the 0.1% of cases where I can't do anything and your computer setup/internet connection is terrible, and therefore this tool is not made for you to use in proper conditions.
You'd better ask for a refund sending a mail with the email you used to register at  sarasa-bot-support@azuriteworlds.com
