### ISSUE TITLE
0 ongoing raids issue

### ISSUE THREAD

**Issue by sujiC** [Masuzu/SarasaBot#82]
Hi @Masuzu 

Same problem as #71 
![default](https://user-images.githubusercontent.com/13200676/36979725-4e66b75c-20c3-11e8-9ac4-ee62ed494fdb.jpg)

I have set DisplayRaids to true, but it still doesn't work.
How can I solve this??

Btw i'm using vpn. Dose that matter??

**Comment by Masuzu** [comment]
Hello,
A VPN might be an issue especially if you are in China.
Also try and set the parameter `DisplayRaids=true` to check whether you have raids captured.
