### ISSUE TITLE
Request: Sound alert with Rise of the Beasts

### ISSUE THREAD

**Issue by meteoshower** [Masuzu/SarasaBot#84]
Hello Masuzu  I have some request about sound alert or close sarasa when  Four Symbols Pendants  are full at 30k  
In the Last ROTB I lost   Soul berry  lot  When  Pendants are full  if it possible i think it really helpful  .
ROTB will Re run soon (Mar-12) 
thanks Masuzu

**Comment by Masuzu** [comment]
Hello,
If the time allows it.

**Comment by meteoshower** [comment]
Event has ended i'll see this update in next re run thanks .

**Comment by meteoshower** [comment]
Rise of the beast is re-run tomorrow i'm still  waiting for this update

**Comment by Masuzu** [comment]
Hello,
I will try and release this feature today or tomorrow.

**Comment by Masuzu** [comment]
The feature is also available in Sarasa Bot as of v1.10.X:
https://gbtools.azurewebsites.net/SarasaBot/en/Home/PatchNotes#1-10-1

**Comment by Masuzu** [comment]
Leaving this open for a few days should issues arise.

**Comment by meteoshower** [comment]
Wow Thanks . i'm going to test it
