### ISSUE TITLE
Going to pending battle but doesn't claim them

### ISSUE THREAD

**Issue by Sundaerae** [Masuzu/SarasaBot#87]
I have this problem that the bot keep cycling between raid list page, then going to pending battles page, but instead of claiming any of it, the bot just return to the raid list. Then because it can't join any raid with 4+ finished battle on pending battle list, it will go to the pending battle list, going back to raid page, rinse and repeat.
This is already happening 4 times today.

**Comment by Masuzu** [comment]
Hello,
This is related to this unfortunate Chrome v65 update:
https://github.com/Masuzu/ZooeyBot/issues/625

**Comment by Sundaerae** [comment]
ok, let me try Chromium v67
I'm not fond of v64 because of the memory leak

**Comment by Sundaerae** [comment]
nope, chromium 67 didn't work. It also has that "no response" thing going on in battle

**Comment by Sundaerae** [comment]
apparently I'm using v67.0.3362 instead of v67.0.3366.
it's working now.
