### ISSUE TITLE
Night Hound Tactical Relocation

### ISSUE THREAD

**Issue by Sundaerae** [Masuzu/SarasaBot#90]
is it possible to add some delay between selecting the 2 characters to be switched?
4 of 10 tries failed because the mouse hover to the 2nd character and then goes to the confirm button without selecting. (or the mouse click isn't registered)

**Comment by po456asd** [comment]
To use the special Nighthound Tactical relocation skill, use the following syntax: 
```
character_1:OnPartyMembers2(3, 5):UseSkill(2)
```
assuming that you assigned the Tactical relocation skill to the second ability slot of your main character. Please note that this feature is untested for uses other than the Nighthound Tactical relocation skill.

![image](https://user-images.githubusercontent.com/13596788/38008550-8bd23bf8-3279-11e8-8e56-5bb4b41dcde6.png)

You can also combine custom waiting time and party member targetting as follows: 
```
character_2:WithWaitTime(<wait_time_in_milliseconds>):OnPartyMember(3):UseSkill(2) or character_2:OnPartyMember(3):WithWaitTime(<wait_time_in_milliseconds>):UseSkill(2).
```

**Comment by Sundaerae** [comment]
no, it's not the problem of I didn't get the syntax right or delay before/after the skill.
Between means after 1st character selected but before the 2nd one.
Sometimes the cursor goes too fast that the 2nd character isn't "clicked" then proceed to the confirm button and tried to click it, but it can't because the 2nd character isn't selected yet.

**Comment by Sundaerae** [comment]
to explain it further, these are the step after clicking relocation amd the selection window pop up:
1) moving cursor to 1st character
2) click
3) moving cursor to 2nd character
4) click
5) moving cursor to confirm button
6) click
7) done

step 4 is often not registered correctly, thus moving to step 5 without doing what it supposed to do, which would of course make step 6 can't be done because the button is disabled.

**Comment by Masuzu** [comment]
Hello,
I took note of the issue.
