### ISSUE TITLE
Websocket Exception

### ISSUE THREAD

**Issue by Sundaerae** [Masuzu/SarasaBot#91]
Sometimes the bot stuck on the raid list page after having this exception. Even though the state said it is trying to joining some raid, it is not.
![exception](https://user-images.githubusercontent.com/31296536/37246471-ed1df254-24db-11e8-97a5-56087dfd877b.png)

**Comment by Sundaerae** [comment]
I think this is beacause of some chromium webGL problem. The "Rats! WebGL hit a snag" thing.
I'll try disabling the hardware acceleration and try again.

**Comment by Masuzu** [comment]
I will note it down.
