### ISSUE TITLE
License renewal

### ISSUE THREAD

**Issue by lamp333** [Masuzu/SarasaBot#92]
Currently cant renew a license due to issues with stripe. Can you take a look at whats going on Masuzu?

**Comment by po456asd** [comment]
more info 
![image](https://user-images.githubusercontent.com/13596788/37279995-155a03c2-261f-11e8-932e-5218cf89cf23.png)

**Comment by Masuzu** [comment]
Hello,
To comply with government regulations, you need to pass the identification verification checks on Stripe before being able to make live transactions: https://stripe.com/docs/dashboard#activating-your-account

This is something strictly related to the terms of service of Stripe and therefore I have no leeway in the process.

**Comment by Masuzu** [comment]
Ah I am afraid I had a misunderstanding. I thought this was related to the Marketplace feature.
This is more troublesome than I expected it to be and will take some time to resolve while an alternative can be found.

**Comment by po456asd** [comment]
ah okai. it was going to tell it about your account xD. take your time.

**Comment by Masuzu** [comment]
https://github.com/Masuzu/ZooeyBot/issues/646
