### ISSUE TITLE
Sarasabot can't join new raids because of pending

### ISSUE THREAD

**Issue by Gepyon** [Masuzu/SarasaBot#96]
I've used SarasaBot in the past and never had this problem until now. The bot would enter the pending page and leave without accepting the finished raids. 

The CMD text would say:
No battle has ended yet. Waiting.

**Comment by tttppp4545** [comment]
I have same issue.

**Comment by Masuzu** [comment]
Hello,
If https://github.com/Masuzu/SarasaBot/issues/88 does not fixes your issue, please check the patch notes of v1.7.4
