### ISSUE TITLE
bot can't use skills

### ISSUE THREAD

**Issue by YumeHaru** [Masuzu/SarasaBot#98]
Hi,

I downloaded last version of bot and tried it with Chrome (v63) and Chronium (v67) and same issue happen: the bot is able to access raid then do nothing.

I don't know why this bug is happening since I coded same way as I do with Zooey bot...
So I attached my script file and a screenshot of Sarasa log.

![sarasabot_2018-03-15_23-59-00](https://user-images.githubusercontent.com/37016519/37496270-d07eb80c-28b1-11e8-8226-465500e32c1d.png)

> Summon(6)
> character_1:UseSkill(4)
> character_1:UseSkill(2)
> character_1:UseSkill(1)
> character_1:UseSkill(3)
> character_2:UseSkill(1)
> character_3:UseSkill(2)
> character_4:UseSkill(2)
> character_4:UseSkill(3)
> 
> if turn == 2 then
> character_2:UseSkill(1)
> end
> 
> if turn == 5 then
>   TerminateBattle()
> end

The only things that changed is that I use Viramate now.

**Comment by YumeHaru** [comment]
@Masuzu 
I've same problem wiht Zooey bot now and I disabled Viramate. I don't understand what I'm doing wrong. It was working fine yesterday.

> if turn == 1 then
> Summon(6)
> character_1:UseSkill(2)
> character_1:UseSkill(4)
> character_2:UseSkill(2)
> character_2:UseSkill(3)
> character_3:UseSkill(1)
> character_3:UseSkill(2)
> character_4:UseSkill(2)
> end

**Comment by YumeHaru** [comment]
I disabled Viramate and I've no more issue, weird.

**Comment by Masuzu** [comment]
Hi,
Did you look at 
https://github.com/Masuzu/SarasaBot/wiki/FAQ#sarasa-is-not-using-skills-or-summons-but-my-lua-scripts-are-valid-viramate-user
