### ISSUE TITLE
Request - Please can you make me a LUA with sarassa ground zero just for leech ? 

### ISSUE THREAD

**Issue by nyky2311** [Masuzu/SarasaBot#99]
Request - Please can you make me a LUA with sarassa ground zero just for leech ? 

I dont know make lua read but still dont understant

I just want threo to use ground zero during leech and leave to another and repeat.

**Comment by Masuzu** [comment]
Hello,
I am sorry but i

**Comment by po456asd** [comment]
```
characters["Threo"]:UseSkill(3)
TerminateBattle()
```
